### ISSUE TITLE
Other neural architectures?

### ISSUE THREAD

**Issue by ShilinC** [NVlabs/tiny-cuda-nn#1]
Hi Thomas,

Really nice work!!! It's great to see that neural networks have been accelerated so much on rendering.

I'm not a GPU expert so I'm wondering if this can be extended to other architectures like CNN besides MLP? If so, that may benefit a lot of neural rendering work that use convolution on images.

Thanks,
Shilin

**Comment by Tom94** [comment]
Hey Shilin, thank you! Yeah, I think there's lots of potential in optimizing other architectures---some of which we're already looking into. If things turn out well, this framework may be incrementally updated in the future. But no promises yet. :)

Cheers!

**Comment by ShilinC** [comment]
Thanks! Looking forward to more!

**Comment by abhi-glitchhg** [comment]
Hey @Tom94 ! Sorry for pinging. 


I know you said no promises, but is there any update in this regard??

Will there be any new architectures supported in future? 

Thanks!
