### ISSUE TITLE
Compilation Error gcc 12.1

### ISSUE THREAD

**Issue by Medoalmasry** [NVlabs/tiny-cuda-nn#109]
### Steps to reproduce error
`cmake . -B build`

CMake Error at /usr/share/cmake/Modules/CMakeDetermineCUDACompiler.cmake:311 (message):
  CMAKE_CUDA_ARCHITECTURES must be valid if set.
Call Stack (most recent call first):
  CMakeLists.txt:25 (PROJECT)

**Upon further inspection, cmake output shows:-**
[CMakeOutput.log](https://github.com/NVlabs/tiny-cuda-nn/files/8834101/CMakeOutput.log)
[CMakeError.log](https://github.com/NVlabs/tiny-cuda-nn/files/8834102/CMakeError.log)
error: #error -- unsupported GNU version! gcc versions later than 11 are not supported! The nvcc flag '-allow-unsupported-compiler'

Steps taken to resolve issue:-

```
cmake . -DCUDA_ENABLED=ON -DCUDA_NVCC_FLAGS="--std c++14 && -allow-unsupported-compiler" 
cmake . -DCUDA_ENABLED=ON -DCUDA_NVCC_FLAGS="--allow-unsupported-compiler" 
cmake . -B build -DCUDA_NVCC_FLAGS="--allow-unsupported-compiler"
```
All of which produce the exact same error.

gcc version: 12.1.0
cmake version: 3.23.1
cuda version: 11.7

**Comment by Tom94** [comment]
I'm afraid you'll have to install GCC 11 or below in order to compile.
