### ISSUE TITLE
Trouble installing tiny-cuda-nn

### ISSUE THREAD

**Issue by Askejm** [NVlabs/tiny-cuda-nn#110]
I'm trying to set up tinycudann for [nvdiffrec](https://github.com/NVlabs/nvdiffrec)
Whenever I try running this command in the readme: `pip install --global-option="--no-networks" git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch` it spits out `ERROR: Command errored out with exit status 1`
![image](https://user-images.githubusercontent.com/55248977/172027279-c0f8d67a-2be9-4f25-b358-d73232f2dc2b.png)
I tried building it manually this way
![image](https://user-images.githubusercontent.com/55248977/172027287-90a7931d-c79c-4a7c-bb8c-47040c05ecc0.png)
but it just fails to build it then spits out the same error.
Tried the command below and get `RuntimeError: Error compiling objects for extension`
[fully_fused_mlp.cu.txt](https://github.com/NVlabs/nvdiffrec/files/8839033/fully_fused_mlp.cu.txt)
I also tried to cmake it, no luck 
![image](https://user-images.githubusercontent.com/55248977/172027376-15496da1-691c-4e1d-8c96-aa8142dd7288.png)

Cuda: 11.3
Python 3.9
Windows 10
CMake 3.23.2
Visual Studio 2019 community
Git 2.36.1
![image](https://user-images.githubusercontent.com/55248977/172027413-1024899a-daf4-440c-a03a-58d16ad4893b.png)
![image](https://user-images.githubusercontent.com/55248977/172027418-cc21769e-a5a3-4814-8e8d-92fc716be1f0.png)

**Comment by avinashc27** [comment]
@Askejm , I'm stuck at the same place.. I have installed Visual studio 16.9.4 with Cuda 11.3 as many suggested to resolve the installation issue but it didn't help. Just wanted to check if you got any luck.

**Comment by mexicantexan** [comment]
Sames...

**Comment by mexicantexan** [comment]
Okay, I was able to solve it by doing these steps, idk if it will work for you, but oh well

Assumptions:
- Windows 10
- Python 3.9

Steps:
1.  Install CUDA Toolkit 11.7 [link](https://developer.nvidia.com/cuda-downloads?target_os=Windows&target_arch=x86_64&target_version=10&target_type=exe_network)
2. Check your environment variables and ensure that the following environment variables are set:
![image](https://user-images.githubusercontent.com/25260617/174413455-ca2faed2-014a-401f-88b4-1dc46aeb8fa5.png)
3. Restart your computer
4. Install Vulkan SDK (someone mentioned to do this in a linux post) NOTE! Make sure that the Vulkan SDK is in your PATH environment variables: [Vulkan SDK Install Instructions](https://vulkan.lunarg.com/doc/view/1.2.148.1/windows/getting_started.html)
5. Restart your computer
6. Now follow the `nvdifferec` setup instructions

**Comment by Askejm** [comment]
YOOOOO it works!
Thank you so much man, I've wanted to try this AI out so badly

**Comment by gnwekge78707** [comment]
> ubuntu 22.04 cuda 11.3 failed to install tinycudann extension for torch . g++: error: /home/lch/Downloads/nvdiffrec-main/tiny-cuda-nn/bindings/torch/build/temp.linux-x86_64-cpython-38/../../dependencies/fmt/src/format.o: No such file or directory g++: error: /home/lch/Downloads/nvdiffrec-main/tiny-cuda-nn/bindings/torch/build/temp.linux-x86_64-cpython-38/../../dependencies/fmt/src/os.o: No such file or directory g++: error: /home/lch/Downloads/nvdiffrec-main/tiny-cuda-nn/bindings/torch/build/temp.linux-x86_64-cpython-38/../../src/common.o: No such file or directory g++: error: /home/lch/Downloads/nvdiffrec-main/tiny-cuda-nn/bindings/torch/build/temp.linux-x86_64-cpython-38/../../src/common_device.o: No such file or directory g++: error: /home/lch/Downloads/nvdiffrec-main/tiny-cuda-nn/bindings/torch/build/temp.linux-x86_64-cpython-38/../../src/cpp_api.o: No such file or directory g++: error: /home/lch/Downloads/nvdiffrec-main/tiny-cuda-nn/bindings/torch/build/temp.linux-x86_64-cpython-38/../../src/cutlass_mlp.o: No such file or directory g++: error: /home/lch/Downloads/nvdiffrec-main/tiny-cuda-nn/bindings/torch/build/temp.linux-x86_64-cpython-38/../../src/encoding.o: No such file or directory g++: error: /home/lch/Downloads/nvdiffrec-main/tiny-cuda-nn/bindings/torch/build/temp.linux-x86_64-cpython-38/../../src/fully_fused_mlp.o: No such file or directory g++: error: /home/lch/Downloads/nvdiffrec-main/tiny-cuda-nn/bindings/torch/build/temp.linux-x86_64-cpython-38/../../src/network.o: No such file or directory g++: error: /home/lch/Downloads/nvdiffrec-main/tiny-cuda-nn/bindings/torch/build/temp.linux-x86_64-cpython-38/tinycudann/bindings.o: No such file or directory error: command '/usr/bin/g++' failed with exit code 1

Same here. Any clues? thanks

**Comment by derickdressel** [comment]
> ubuntu 22.04 cuda 11.3 failed to install tinycudann extension for torch . g++: error: /home/lch/Downloads/nvdiffrec-main/tiny-cuda-nn/bindings/torch/build/temp.linux-x86_64-cpython-38/../../dependencies/fmt/src/format.o: No such file or directory g++: error: /home/lch/Downloads/nvdiffrec-main/tiny-cuda-nn/bindings/torch/build/temp.linux-x86_64-cpython-38/../../dependencies/fmt/src/os.o: No such file or directory g++: error: /home/lch/Downloads/nvdiffrec-main/tiny-cuda-nn/bindings/torch/build/temp.linux-x86_64-cpython-38/../../src/common.o: No such file or directory g++: error: /home/lch/Downloads/nvdiffrec-main/tiny-cuda-nn/bindings/torch/build/temp.linux-x86_64-cpython-38/../../src/common_device.o: No such file or directory g++: error: /home/lch/Downloads/nvdiffrec-main/tiny-cuda-nn/bindings/torch/build/temp.linux-x86_64-cpython-38/../../src/cpp_api.o: No such file or directory g++: error: /home/lch/Downloads/nvdiffrec-main/tiny-cuda-nn/bindings/torch/build/temp.linux-x86_64-cpython-38/../../src/cutlass_mlp.o: No such file or directory g++: error: /home/lch/Downloads/nvdiffrec-main/tiny-cuda-nn/bindings/torch/build/temp.linux-x86_64-cpython-38/../../src/encoding.o: No such file or directory g++: error: /home/lch/Downloads/nvdiffrec-main/tiny-cuda-nn/bindings/torch/build/temp.linux-x86_64-cpython-38/../../src/fully_fused_mlp.o: No such file or directory g++: error: /home/lch/Downloads/nvdiffrec-main/tiny-cuda-nn/bindings/torch/build/temp.linux-x86_64-cpython-38/../../src/network.o: No such file or directory g++: error: /home/lch/Downloads/nvdiffrec-main/tiny-cuda-nn/bindings/torch/build/temp.linux-x86_64-cpython-38/tinycudann/bindings.o: No such file or directory error: command '/usr/bin/g++' failed with exit code 1

Same.  I prevented the installer's cleanup process and digging through the temp files it looks like whatever's supposed to build the files isn't executing, but I dunno why.

Install succeeds for me outside of a conda environment, but I need conda for this. :(

Any ideas why conda would prevent .o files from being built?
