### ISSUE TITLE
Compatibility with CUDA 10.1

### ISSUE THREAD

**Issue by lenismerino** [NVlabs/tiny-cuda-nn#112]
Hello, kudos to the team for sharing this project! My goal is to use instant-ngp on Ubuntu 18.04 and compilation fails at this step. I was wondering if I could get workaround suggestions on the code (besides removing the CUDA version checks) to soften the requirements and compile the framework using CUDA version 10.1 (Driver version 418.87) or to get confirmation that it is indeed not possible due to usage of specific functionality not present on this version of CUDA.

Thanks

**Comment by Tom94** [comment]
Hi there, sorry, we do not plan to officially support CUDA 10.1 or earlier.
