### ISSUE TITLE
Get nested optimizer

### ISSUE THREAD

**Issue by jc211** [NVlabs/tiny-cuda-nn#140]
Can we add a method to optimizer that allows us to access the nested optimizer if it exists?

```cpp
virtual std::shared_ptr<Optmizer> nested() { return std::shared_ptr<Optimizer>(); }
```

**Comment by Tom94** [comment]
Totally, please feel free to add it to your other PR. Although I'd prefer the equivalent, but clearer form:
```c++
virtual std::shared_ptr<Optmizer> nested() { return nullptr; }
```

**Comment by jc211** [comment]
Are you ok with me making the m_nested optimizers shared_ptrs instead of unique_ptrs?

**Comment by Tom94** [comment]
Yeah -- this would be in line with similar APIs throughout the framework (e.g. `NetworkWithInputEncoding::encoding() -> const std::shared_ptr<Encoding<T>>&`).

This makes me think
```c++
virtual const std::shared_ptr<Optmizer>& nested() const { throw std::runtime_error{"Optimizer does not support nesting."}; }
virtual bool has_nested() const { return false; }
```
would be a better interface, though. That way, there'd a distinction between optimizers that _can_ have nesting, but just don't have a nested optimizer set (yet), and optimizers that fundamentally can't have nested ones (like Adam). Could we go with this one?

**Comment by jc211** [comment]
We can err on the side of caution and make it a const pointer I suppose. Not sure if thats too limited at this point.

**Comment by Tom94** [comment]
I don't think it's limiting at all: it's just the shared ptr struct itself that's `const&` -- i.e. it won't create a new shared ptr and increment/decrement a reference count if all you need is to temporarily access the object. Other than that, you can do the same things with it as if the method returned a regular shared ptr.

Thanks for making the change!

**Comment by Tom94** [comment]
Implemented in https://github.com/NVlabs/tiny-cuda-nn/pull/139
