### ISSUE TITLE
Maximum grid dimension

### ISSUE THREAD

**Issue by jonathanventura** [NVlabs/tiny-cuda-nn#150]
Is there any reason the grid can't go above 7 dimensions?  Is it simply a matter of adding more primes to this list?

    	constexpr uint32_t primes[7] = { 1u, 2654435761u, 805459861u, 3674653429u, 2097192037u, 1434869437u, 2165219737u };

And, if so, is there a principled way to add more primes to the list?

**Comment by Tom94** [comment]
Hi there, while you _could_ go to higher dimensions by adding primes, I'd strongly recommend against it. N-d interpolation scales exponentially with d, which quickly makes lookups prohibitive.

Plus, high-dimensional hash tables are very bad at compactly representing a lower-D signal. Think, for example, of a 4-D scene (space + time) that happens to be (mostly) static in the time dimension. One would hope that, in this case, the 4-D grid would perform equally well as a 3-D variant that doesn't contain the time dimension, but that wouldn't actually be the case. Any step in the (static) time dimension would also scramble the hash in the other 3 dimensions.

**Comment by jonathanventura** [comment]
Got it -- thanks for the explanation.
