### ISSUE TITLE
Large prime number result in overflow

### ISSUE THREAD

**Issue by Linyou** [NVlabs/tiny-cuda-nn#151]
In the fast_hash function
```
constexpr uint32_t primes[7] = { 1u, 2654435761u, 805459861u, 3674653429u, 2097192037u, 1434869437u, 2165219737u };

uint32_t result = 0;

TCNN_PRAGMA_UNROLL
for (uint32_t i = 0; i < N_DIMS; ++i) {
    result ^= pos_grid[i] * primes[I];
}

```

The prime numbers are extremely large, and the pos_grid value is in the range of (0, scale), this may result in overflow for uint32 type when dong multiplication on these two values. Is this behavior intentional ?

**Comment by Tom94** [comment]
Yes, that's intentional. Since the hash table size, which is getting modulo'd in the end, is a power of two, there's no effect from the implicit modulo 2^32 that an `uint32_t` overflow causes.

**Comment by Linyou** [comment]
Thanks!
