### ISSUE TITLE
A quick question on Spherical Harmonics

### ISSUE THREAD

**Issue by Totoro97** [NVlabs/tiny-cuda-nn#152]
Hi, thanks for this awesome project! I have a quick question on the input of the sphere harmonics. I see the inputs are re-scaled in this line:

https://github.com/NVlabs/tiny-cuda-nn/blob/657a54124edd5b946d050b30b0b3838afc543e42/include/tiny-cuda-nn/encodings/spherical_harmonics.h#L66

Does this line mean rescale the input range from [0, 1] to [-1, 1]?

Thanks in advance!

**Comment by Tom94** [comment]
Yes. __tiny-cuda-nn__'s encodings all expect inputs within [0,1]^n by convention, so if you'd like to feed direction vectors in S^2 into the spherical harmonics encoding, you need to first squish them into [0,1]^3. The code that you highlight undoes this squishing. Cheers!

**Comment by Totoro97** [comment]
Thanks for your quick reply~
