### ISSUE TITLE
Creating fully fused with existing weights

### ISSUE THREAD

**Issue by kommander** [NVlabs/tiny-cuda-nn#16]
Hi, thanks for this! I cannot seem to find anything in the docs about how to create/init a network with existing weights, or even export and store trained weights. Maybe I've missed that. Could anyone point me to the docs for that or give a hint?

**Comment by Tom94** [comment]
Hi! We don't really have a true documentation -- this project is meant more for reproduction than as a fully-featured system.

However! I can serve with Python bindings `testbed.load_snapshot(filename)` and `testbed.save_snapshot(filename)`. (see [src/python_api.cu](src/python_api.cu))

Refer to `Testbed::load_snapshot` and `Testbed::save_snapshot` for the programmatic details of how these work.

The Testbed GUI also has dedicated "snapshot" buttons for loading/restoring.

**Comment by Tom94** [comment]
Oh snap, I got confused about which repository this is. Leaving the text above intact in case it's still helpful.

__tiny-cuda-nn__'s mechanism for loading and storing weights is described in the following comment: https://github.com/NVlabs/tiny-cuda-nn/issues/6#issuecomment-988621068

I'll leave this issue open to remind myself to extend the readme/docs with the relevant info.

**Comment by kommander** [comment]
Thanks for the immediate answer. Yes, got confused there for a second :) The description from the comment #6 looks fine, I think I can work with that, awesome!
