### ISSUE TITLE
question about pytorch extension

### ISSUE THREAD

**Issue by william0620** [NVlabs/tiny-cuda-nn#160]
Hi, I 've finished the complication part, and when it comes to pytorch extension after entering  `pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch`
it prints the error as following:

`Cloning https://github.com/NVlabs/tiny-cuda-nn/ to /tmp/pip-req-build-z__fsf1o
  Running command git clone --filter=blob:none --quiet https://github.com/NVlabs/tiny-cuda-nn/ /tmp/pip-req-build-z__fsf1o
  Resolved https://github.com/NVlabs/tiny-cuda-nn/ to commit 0efe0698b22f424cd98c4c0d2c648f872f0480f5
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      /home/text2img/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/torch/cuda/__init__.py:83: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW (Triggered internally at  ../c10/cuda/CUDAFunctions.cpp:109.)
        return torch._C._cuda_getDeviceCount() > 0
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-z__fsf1o/bindings/torch/setup.py", line 30, in <module>
          raise EnvironmentError("Unknown compute capability. Specify the target compute capabilities in the TCNN_CUDA_ARCHITECTURES environment variable or install PyTorch with the CUDA backend to detect it automatically.")
      OSError: Unknown compute capability. Specify the target compute capabilities in the TCNN_CUDA_ARCHITECTURES environment variable or install PyTorch with the CUDA backend to detect it automatically.
      No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-11.7'
      Building PyTorch extension for tiny-cuda-nn version 1.6
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

**Comment by william0620** [comment]
Besides, if I use the local clone, the error is as following:
`/site-packages/torch/cuda/__init__.py:83: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW (Triggered internally at  ../c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-11.7'
Building PyTorch extension for tiny-cuda-nn version 1.6
Traceback (most recent call last):
  File "setup.py", line 30, in <module>
    raise EnvironmentError("Unknown compute capability. Specify the target compute capabilities in the TCNN_CUDA_ARCHITECTURES environment variable or install PyTorch with the CUDA backend to detect it automatically.")
OSError: Unknown compute capability. Specify the target compute capabilities in the TCNN_CUDA_ARCHITECTURES environment variable or install PyTorch with the CUDA backend to detect it automatically.`

**Comment by william0620** [comment]
Update: By the way, i use 2080ti, however, when I test on 3090, it works.

**Comment by william0620** [comment]
I just rebooted, and it worked really strange

**Comment by venatiodecorus** [comment]
I'm running into this same issue while trying to install this to work with nerfstudio. Rebooting did not fix it for me. Running a 2070 Super.

**Comment by andrewyguo** [comment]
I also got this error. I noticed that `torch.cuda.is_available()` was returning False. I was able to fix this by reinstalling pytorch with the instructions here: 

https://pytorch.org/get-started/previous-versions/
