### ISSUE TITLE
meta-learning support

### ISSUE THREAD

**Issue by thuanz123** [NVlabs/tiny-cuda-nn#162]
Hi, I want to ask if the pytorch binding of this framework supports meta-learning where we pass a predicted weight from a hyper network (from Pytorch) to the fully fused mlp

**Comment by Tom94** [comment]
Yes, that should work out-of-the-box. If you run into any problems that a regular PyTorch MLP doesn't exhibit, please feel free to open a new issue for those.

**Comment by 07hyx06** [comment]
Hi, @Tom94 I want to ask if the pytorch binding of this framework supports meta-learning where we pass a predicted weight from a hyper network (from Pytorch) to the hash encoder (tcnn.Encoding with otype hashgrid )?

I try to use `hash_encoder.state_dict()["params"]=hash_feature` in the forward pass where `hash_feature=nn.parameter.Parameter(torch.zeros_like(hash_encoder.state_dict()["params"]))`, but it seems not work. After training, the hash_feature still remains 0.
