### ISSUE TITLE
Question regarding cutlass dependency

### ISSUE THREAD

**Issue by mgrabban** [NVlabs/tiny-cuda-nn#165]
Hello,

This is a nice repo! But I have a question.
Is it possible to get rid of the cutlass dependency completely when using only fully fused MLP or is it still required?
If it was possible, one could to convert the code to HIP or SYCL.
I found that inside tiny-cuda-nn/src/fully_fused_mlp.cu cutlass is referred to, probably for matrix multiplication.

BTW when I run on an A100, it takes 0.41s while on an RTX2060 it takes 1.11s.

Thanks!

**Comment by mgrabban** [comment]
I think I found the answer in your [paper](https://tom94.net/data/publications/mueller21realtime/mueller21realtime.pdf) where towards the end of Section 4 it says 

> We compute these additional matrix multiplications using the general matrix multiplication (GEMM) routines of the CUTLASS template library (in split-k mode) as we were unable to produce a faster implementation ourselves.

So cutlass is indeed needed. Thanks.

**Comment by Tom94** [comment]
Hi, yes, that's the answer. The path of least resistance to avoid the dependency is probably to replace it with cuBLAS calls -- perhaps there exists an equivalent in HIP / SYCL
