### ISSUE TITLE
A question about CUDA Kernels 

### ISSUE THREAD

**Issue by mah-asd** [NVlabs/tiny-cuda-nn#173]
Hi, 
Thank you for your impressive work. 
I have a question about using tiny-cuda-n.n. 
Based on my understanding, we can use it instead of PyTorch for optimization problems. right? 
And then, if we have a CUDA kernel somewhere in our code, we don't have to write a costume backward function to calculate the gradients?

**Comment by Tom94** [comment]
Hi, no, it's the opposite. In __tiny-cuda-nn__, every module has a custom backward function. There's no autograd in this framework. Cheers!

**Comment by mah-asd** [comment]
Thank you so much; I really appreciate it.
