### ISSUE TITLE
Very high memory usage at compilation time

### ISSUE THREAD

**Issue by libeanim** [NVlabs/tiny-cuda-nn#175]
Hi,

I'm in the process of setting up [nerfstudio](https://docs.nerf.studio/en/latest/quickstart/installation.html) and need to install tiny-cuda-nn via
```
pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
```

I have currently ~130GB of RAM alllocated for this job but that does not seem to be enough.
![Screenshot from 2022-10-19 13-39-20](https://user-images.githubusercontent.com/1412303/196681227-0e863ce5-d111-4190-a438-2190df332c6d.png)

Terminal output so far:
```
$ pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
Collecting git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
  Cloning https://github.com/NVlabs/tiny-cuda-nn/ to /scratch_local/ahochlehnert48-1936838/tmp/pip-req-build-zbi99zii
  Running command git clone --filter=blob:none --quiet https://github.com/NVlabs/tiny-cuda-nn/ /scratch_local/user-1936838/tmp/pip-req-build-zbi99zii
  Resolved https://github.com/NVlabs/tiny-cuda-nn/ to commit 93ed3e38b9bf25bc159d9dcff93d78472c8e1141
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: tinycudann
  Building wheel for tinycudann (setup.py) ... | 
```

**How much memory do I need in order to build tiny-cuda-nn using pip?**

Thx

**Comment by alvaro-budria** [comment]
@libeanim In your screenshot, it looks like the installation did not crash. Are you referring to the fact that the installation takes extremely long? If so, I'm facing the same problem as you, as I've been waiting for more than 2h now.

**Comment by libeanim** [comment]
The problem was that the memory usage was higher than expected. It crashed and I restarted it with more RAM in the hope it is enough now (Because I am running it on a cluster I have to set the maximum amount of RAM that the cluster allocates to this job beforehand. My current limit is 180GB, seems to be OK for now)

But yes, the waiting time is another problem, my job currently runs for 7.5h with no indication of being done soon.
It does not appear to have crashed yet.

**Comment by libeanim** [comment]
Not sure what the issue in my original setup was but using the docker image `nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04` solved the problem for me.
Everything compiled and required **way less** memory and time.

**Comment by Tom94** [comment]
I'd like to look deeper into this, given that I've also experienced weird memory usage in one of the CI runners -- could you let me know the OS version, GCC version, and CUDA version of the setup that had very high RAM usage?

Based on my experience with the aforementioned CI runner, upgrading both GCC and CUDA solved the problem (like in your use of the docker image), but I'm not sure if both are actually required.

**Comment by lambdald** [comment]
When compiling tiny-cuda-nn/bindings/torch/src/encoding.o, I encountered the same problem. 32G memory is not enough, and the process will be killed. The system information is as follows:
OS: Ubuntu 22.04 LTS
GCC: 9.4.0
CUDA: 11.3

**Comment by alvaro-budria** [comment]
In my case, I was getting the error with
* GCC: 7.5.0
* CUDA: `CUDA_HOME=/usr/local/opt/cuda-11.3/`
After switching to `CUDA_HOME=/usr/local/opt/cuda-11.1/` it worked.

**Comment by DummyNodeHead** [comment]
Same as @lambdald. My compilation is always stuck when building CUDA object **CMakeFiles/tiny-cuda-nn.dir/src/encoding.cu.o**

I have 32G mem, and I expand SWAP to 32G but ERROR 137 still occurs.

Moreover, when compiling, the footprints of my memory and swap are extremly high.

- OS: Ubuntu 22.04 LTS
- GCC: 9.4.0
- CUDA: 11.3

**Comment by DummyNodeHead** [comment]
You can use v1.4 as an alternative. v1.4 can be successfully installed for me.

**Comment by 3a1b2c3** [comment]
happens to me both on windows 11 and ubuntu 20, previous versions went ok, cuda 11.3

**Comment by 3a1b2c3** [comment]
> You can use v1.4 as an alternative. v1.4 can be successfully installed for me.

11.4?

**Comment by RohanChacko** [comment]
> ```
> pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
> ```

Hi, what was the total compilation time with the run that worked finally? Thanks!

**Comment by RohanChacko** [comment]
> @Tom94 Yes my hunch was also that it is some GCC/CUDA version issue.
> 
> **For the runs which had the issue:** I used the docker image `nvidia/cuda:11.3.1-cudnn8-devel-ubuntu20.04`
> 
> * OS: Ubuntu 20.04 LTS
> * GCC: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
> * CUDA: cuda_11.3.r11.3/compiler.29920130_0
> 
> **For the runs that worked:** I used `nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04`
> 
> * OS: Ubuntu 22.04 LTS
> * GCC: (Ubuntu 11.2.0-19ubuntu1) 11.2.0
> * CUDA: cuda_11.8.r11.8/compiler.31833905_0
> 
> In both containers I manually installed `gcc`, `build-essentials` and `conda`. The `conda`, `python` and `pip` version was the same across all runs:
> 
> * Python: 3.8
> * Pip: 22.3

Hi, what was the total compilation time with the run that worked finally? Thanks!

**Comment by DummyNodeHead** [comment]
> 

Nope, tiny-cuda-nn 1.4. See here for more. It works for me.
https://github.com/NVlabs/tiny-cuda-nn/releases

**Comment by DummyNodeHead** [comment]
> > You can use v1.4 as an alternative. v1.4 can be successfully installed for me.
> 
> 11.4?

Nope. tiny-cuda-nn v1.4. See [here](https://github.com/NVlabs/tiny-cuda-nn/releases) for more. It works for me.

**Comment by Tom94** [comment]
Thanks for the help, everyone. I was able to narrow it down to the combination of CUDA 11.3 + GCC thing and work around the issue from there. Please feel free to re-open this thread if the same error resurfaces.
