### ISSUE TITLE
Hash table second derivitive with respect to the input

### ISSUE THREAD

**Issue by Mehdishishehbor** [NVlabs/tiny-cuda-nn#185]
Hi,

Thanks for your great research. Does hash table work for second derivative with respect to x (input)? or it only works for weights? 

for example, let say we have this sequence of passing info:
`x -> hash table -> neural network -> y`

Now I want to get the second partial derivative of y with respect to x (d2y/dx2).

Please let me know.

Thanks,
Mehdi

**Comment by Tom94** [comment]
Hi, yes, this should be supported out of the box.

Importantly, you need to use
```json
"interpolation": "Smoothstep",
```
when configuring the encoding. When using the default linear interpolation, the second derivative is always zero and hence not very useful.
