### ISSUE TITLE
illegal memory access error

### ISSUE THREAD

**Issue by pierre-wilmot** [NVlabs/tiny-cuda-nn#189]
Hi, 

I'm unable to run a really simple test, getting an illegal memory access error.
Here is the code sample:

```c++
{
  const char *config = R"({"base_resolution":32,"log2_hashmap_size":16,"n_features_per_level":2,"n_levels":20,"otype":"HashGrid","per_level_scale":1.5})";
  nlohmann::json config_json = nlohmann::json::parse(config);
  tcnn::GridEncoding<float> *g = tcnn::create_grid_encoding<float>(3, config_json);

  tcnn::GPUMatrix<float> input(g->n_pos_dims(), 1);
  tcnn::GPUMatrix<float> output(g->padded_output_width(), 1);
  input.memset(0);
  
  std::unique_ptr<tcnn::Context> c = g->forward(input, &output);

  std::vector<float> result_host(output.n_elements());
  CUDA_CHECK_THROW(cudaMemcpy(result_host.data(), output.data(), output.n_bytes(), cudaMemcpyDeviceToHost));
}
```

This results in:

```
/tmp/tiny-cuda-nn/test/grid.cu:6: FAILED:
due to unexpected exception with message:
  /tmp/tiny-cuda-nn/test/grid.cu:19 cudaMemcpy(result_host.data(), output.data
  (), output.n_bytes(), cudaMemcpyDeviceToHost) failed with error an illegal
  memory access was encountered
```
and
```
Could not free memory: /tmp/tiny-cuda-nn/test/../include/tiny-cuda-nn/gpu_memory.h:141 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /tmp/tiny-cuda-nn/test/../include/tiny-cuda-nn/gpu_memory.h:141 cudaFree(rawptr) failed with error an illegal memory access was encountered
```

The full code is available at https://github.com/pierre-wilmot/tiny-cuda-nn/tree/Test (branch Test)

I can get the error to disapear by commenting out line [347 in grid.h](https://github.com/pierre-wilmot/tiny-cuda-nn/blob/e7c30c8150c3ccaa50396d0578b0612c1ab5f039/include/tiny-cuda-nn/encodings/grid.h#L347
)
```c++
encoded_positions[i + (level * N_FEATURES_PER_LEVEL + f) * num_elements] = result[f];
```

Could there be a mistake in the index calculation? I does fell a bit unnatural to me.
If not, what am I missing  ?

I've tried various versions (with passing a cuda stream to both the matrix constructors and forward call), but I never got it to run successfully.

Best,
Pierre

**Comment by Tom94** [comment]
Hi, thanks for reporting.

The batch size must be a multiple of `tcnn::batch_size_granularity` (==128 at the moment). If you'd like to process fewer elements at a time, you can simply make the matrices 128 elements wide and ignore the additional entries in the result. (If you are training, though, make sure to pad either with duplicates or with input/output pairs that produce a zero loss.)

I apologize for this having been unclear -- honestly, I'm shocked this problem hasn't come up earlier for someone else. I just added guards (latest `master`) that'll catch this rather than letting things crash unpredictably. I'll also add mention it in the README.

**Comment by pierre-wilmot** [comment]
Hey, thanks for the reply, no luck using a 128 batch size though.
Here is the current iteration of the code. The assertions all pass, but the program still crashes with the same errors.
Updated code pushed to same branch.

```c++
TEST_CASE("3D All 0", "GRID")
{
  const char *config = R"({"base_resolution":32,"log2_hashmap_size":16,"n_features_per_level":2,"n_levels":20,"ot\
ype":"HashGrid","per_level_scale":1.5})";
  nlohmann::json config_json = nlohmann::json::parse(config);
  tcnn::GridEncoding<float> *g = tcnn::create_grid_encoding<float>(3, config_json);

  // Current codebase only accept multiple of tcnn::batch_size_granularity
  unsigned int batch_size = tcnn::batch_size_granularity;
  REQUIRE(batch_size == 128);

  tcnn::GPUMatrix<float> input(g->n_pos_dims(), batch_size);
  tcnn::GPUMatrix<float> output(g->padded_output_width(), batch_size);
  input.memset(0);

  REQUIRE(input.n_elements() == 3 /* dimensions */ * 128 /* batch size */);
  REQUIRE(output.n_elements() == 2 /* feture per level */ * 20 /* levels*/ * 128 /* batch size */);

  std::unique_ptr<tcnn::Context> c = g->forward(input, &output);

  std::vector<float> result_host(output.n_elements());
  CUDA_CHECK_THROW(cudaMemcpy(result_host.data(), output.data(), output.n_bytes(), cudaMemcpyDeviceToHost));
}
```

**Comment by Tom94** [comment]
Oh, I think `g->initialize_params(...)` is missing. Normally, this is done for you by `Trainer`, but since you don't use one, you'll have to allocate parameters yourself.

I really need to spend some time to make the API yield meaningful errors rather than outright causing undefined behavior. Sorry about that.

**Comment by pierre-wilmot** [comment]
Thanks ! 😄 
That seems to be the answer.

Here is the minimum working example I got.

```c++
TEST_CASE("3D All 0", "GRID")
{
  const char *config = R"({"base_resolution":32,"log2_hashmap_size":16,"n_features_per_level":2,"n_levels":20,"ot\
ype":"HashGrid","per_level_scale":1.5})";
  nlohmann::json config_json = nlohmann::json::parse(config);
  tcnn::GridEncoding<float> *g = tcnn::create_grid_encoding<float>(3, config_json);

  // Parameters are NOT an encapsulated member of GridEncoding.
  // We need to allocate them manually and set them.
  size_t n_params = g->n_params();
  REQUIRE(n_params == 2555904);
  tcnn::GPUMemory<char> params_buffer;
  params_buffer.resize(sizeof(float) * n_params);
  float *params = (float*)(params_buffer.data());
  float *inference_params = params;
  float *backward_params = nullptr;
  float *gradients = nullptr;
  // Using the same values for params and inference params in this test, not setting the rest.
  g->set_params(params, inference_params, backward_params, gradients);

  unsigned int batch_size = 1;
  tcnn::GPUMatrix<float> input(g->n_pos_dims(), batch_size);
  tcnn::GPUMatrix<float> output(g->padded_output_width(), batch_size);
  input.memset(0);

  REQUIRE(input.n_elements() == 3 /* dimensions */ * 1 /* batch size */);
  REQUIRE(output.n_elements() == 2 /* feture per level */ * 20 /* levels*/ * 1 /* batch size */);

  std::unique_ptr<tcnn::Context> c = g->forward(input, &output);

  std::vector<float> result_host(output.n_elements());
  CUDA_CHECK_THROW(cudaMemcpy(result_host.data(), output.data(), output.n_bytes(), cudaMemcpyDeviceToHost));
}
```

It seems that setting the batch size to 1 actually works (for the test I'm running), or at least runs without crashing.

Are you interrested in a PR with the changes to set up unit tests? There is not much too it for now, but I find it very helpfull to be able to experiments with components in isolation. And it will avoid someone else spending time setting up the CMake boilerplate (since that is usually a pain point for most devs).

**Comment by Tom94** [comment]
I'm definitely interested -- unit tests would be great to have!

Yeah, batch size 1 might work with _some_ components, but the code currently doesn't expose which ones they are. I think for now the best approach is to catch all violations of `tcnn::batch_size_granularity` and to consider relaxing that by exposing a per-component granularity in the future.
