### ISSUE TITLE
where is the setup.py ......#_# 

### ISSUE THREAD

**Issue by xxsgh** [NVlabs/tiny-cuda-nn#201]
![image](https://user-images.githubusercontent.com/102399568/202959603-3fe0ba59-134a-440f-86a0-fa415a41a84f.png)

**Comment by swframe** [comment]
Please check the install docs more carefully?
Look at this line
`pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch`

See that **/#subdirectory=bindings/torch** at the end. The setup.py is in that dir.
