### ISSUE TITLE
Error while building wheel for tinycudann

### ISSUE THREAD

**Issue by Klabautermann95** [NVlabs/tiny-cuda-nn#203]
Hello there

I am trying to get nerfstudio running on my device. 
Environment is created and conda installed, 
Python 3.8. active
CUDA 11.3 is set up and tested with the samples
VS 2019 installed
Pytorch versions installed as mentioned in the documentation

Now when it comes to the second step of the dependencies:
_pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch_

I get the errors shown in the screenshot. (I already tried it with a cloned, local repo, same error)
It seems to be a problem with the setup.py in the sub-process and the building of the wheels crashes. If anybody could help me or give me hints on a possible solution, would be very appreciated! 

Thanks in advance

![Screenshot 2022-11-25 232024](https://user-images.githubusercontent.com/102353180/204059923-7409bcfc-bf50-4151-9bbd-04d0a0f13f15.jpg)

**Comment by ericdepotter** [comment]
Have you been able to solve this issue?

**Comment by trltzy** [comment]
I have similar problem, anyone knows how to fix it? thx

**Comment by flyingtief47** [comment]
Have you been able to solve this issue?

**Comment by THUROI0787** [comment]
Also waiting for solutions......

**Comment by Larerr** [comment]
Also waiting for solutions......
