### ISSUE TITLE
NameError in modules.py

### ISSUE THREAD

**Issue by lucasthahn** [NVlabs/tiny-cuda-nn#209]
While trying to run `ns-train` in `nerfstudio` using the PyTorch bindings, I started running into this error starting this morning: 

```
 File "/opt/conda/lib/python3.8/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/function.py", line 253, in apply
    return user_fn(self, *args)
  File "/opt/conda/lib/python3.8/site-packages/tinycudann/modules.py", line 85, in backward
    return None, null_tensor_to_none(input_grad), null_tensor_to_none(params_grad), None
NameError: name 'params_grad' is not defined
```

This seems to be related to commit `ea9e700ed22014e4287ef4afbff75442d0e273fc` in which `weights_grad` was renamed to `params_grad` - it was renamed on line 85 of `modules.py`, but not on line 83. The code works fine when I rename `params_grad` to `weights_grad` on line 85. 

Installed using the following (on Ubuntu 20.04):

```
python3 -m pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch 
```

**Comment by Tom94** [comment]
I'm confused -- the rename seems to have gone through. Line 83 looks correct on `master`
https://github.com/NVlabs/tiny-cuda-nn/blob/ea09e160960ee37a067edb4ad65a255705307961/bindings/torch/tinycudann/modules.py#L83

**Comment by lucasthahn** [comment]
Strange! Things are working fine for me from cloning and building the torch bindings from the latest `master`, so that change is also in on my end. Is it possible that the `git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch` is pointing somewhere else?  

Also, it's definitely entirely possible that I just pulled from that link at an inopportune time between commits or something (was working from a Docker image built about 6 hours ago)

**Comment by Tom94** [comment]
Oh, that could well be. I did a few manual edits to get the git history into a clean state and might have missed a rename inbetween. Going to close this issue for now; please feel free to re-open it if the problem comes up again!

**Comment by lucasthahn** [comment]
Gotcha - thanks so much for an amazing tool!
