### ISSUE TITLE
Condition to check the Hash table size  

### ISSUE THREAD

**Issue by Mehdishishehbor** [NVlabs/tiny-cuda-nn#218]
Hi, 

In the paper, there is a condition to check whether to use the 1:1 mapping (no hash encoding) or hash table. At least this is my understanding. However, I could not find this condition in the code. Is there such condition in the code?

<img width="388" alt="image" src="https://user-images.githubusercontent.com/94387791/207415668-397c3ab6-3e55-429a-aa62-72dca0f634e2.png">

Thanks,
Mehdi

**Comment by Tom94** [comment]
Yep, it's the `hashmap_size < stride` check in the `grid_index(...)` function.
