### ISSUE TITLE
CudaGraph not thread-safe?

### ISSUE THREAD

**Issue by chanket** [NVlabs/tiny-cuda-nn#225]
Hello,

I encountered a `CudaGraph` error when I try to do multi-threaded instant-ngp rendering. I created 2 instant-ngp instances on 2 GPUs based on `CutlassMLP` and started rendering together, but the program crashed on the following line:

https://github.com/NVlabs/tiny-cuda-nn/blob/6ccf5ad7b03d15241ffbd392b3579168df73faa5/include/tiny-cuda-nn/cuda_graph.h#L97

I read the implementation of class `CudaGraph`, and find that it depends on a static `std::deque`:

https://github.com/NVlabs/tiny-cuda-nn/blob/6ccf5ad7b03d15241ffbd392b3579168df73faa5/include/tiny-cuda-nn/cuda_graph.h#L44

I suppose it is not thread-safe even if we are manipulating different instances of `CudaGraph`, including `CutlassMLP` and others that references `CudaGraph`.

Is there any workaround to handle this issue, such as (I'm not very sure) :
* using a dedicated `std::deque` for each `CudaGraph` instance, or
* adding a lock?

**Comment by Tom94** [comment]
Hi, could you pull latest master and see whether it works now? I made `s_current_captures` a `thread_local` variable, which should alleviate the problem.

A handful of other places in __tiny-cuda-nn__ are unfortunately also not threadsafe. I'd like to move to full thread safety in the future, but can not commit to a specific timeline. Please feel free to report additional thread safety issues as they come up (if they do).

**Comment by chanket** [comment]
> Hi, could you pull latest master and see whether it works now? I made `s_current_captures` a `thread_local` variable, which should alleviate the problem.
> 
> A handful of other places in **tiny-cuda-nn** are unfortunately also not threadsafe. I'd like to move to full thread safety in the future, but can not commit to a specific timeline. Please feel free to report additional thread safety issues as they come up (if they do).

The latest master works correctly. Thank you!
