### ISSUE TITLE
CUDA version too low.  tiny-cuda-nn require CUDA 10.2 or higher

### ISSUE THREAD

**Issue by Justinfungi** [NVlabs/tiny-cuda-nn#238]
Command : `cmake . -B build`

Error msg:

-- Obtained CUDA architectures automatically from installed GPUs
-- Targeting CUDA architectures: 75
CMake Error at CMakeLists.txt:212 (message):
  CUDA version too low.  tiny-cuda-nn require CUDA 10.2 or higher.

-- Configuring incomplete, errors occurred!
See also "/home/wk1user2/3D/tiny-cuda-nn/build/CMakeFiles/CMakeOutput.log".

I have also updated the Cuda toolkit using conda install cudatoolkit. how can I solve the issue

**Comment by Justinfungi** [comment]
i think it is due to the remote server. i cannot change the core setting of remote server. Solve: ask for system manager to help

**Comment by Justinfungi** [comment]
i think it is due to the remote server. i cannot change the core setting of remote server. Solve: ask for system manager to help

**Comment by potoyeee** [comment]
Did you solve this problems？ I install a new cuda11.7 but it still have this problem.

**Comment by h3clikejava** [comment]
Did you solve this problems？ I install a new cuda11.3 but it still have this problem.
