### ISSUE TITLE
nvcc fatal   : Unsupported gpu architecture 'compute_89'

### ISSUE THREAD

**Issue by Lucklycat** [NVlabs/tiny-cuda-nn#239]
whern i install tiny_cuda_nn,there have a erroe:
![image](https://user-images.githubusercontent.com/17697877/211542468-1347e59b-d54f-439a-b704-032d10265f5f.png)

My environment：
system：ubuntu
Graphics card：rtx4090
CUDA Version：11.3
pytorch:1.10
python:3.9

I checked online and found that the calculation power does not match. How should I solve it？
thanks

**Comment by Tom94** [comment]
Either
- upgrade CUDA or
- target an older GPU version (may run slower) that is supported by your installed version of cuda (11.3). E.g. by setting the environment variable `TCNN_CUDA_ARCHITECTURES=86`

**Comment by Lucklycat** [comment]
> 
thanks.      Which CUDA version do I need to upgrade to?
