### ISSUE TITLE
Wrong config option in sample code

### ISSUE THREAD

**Issue by danielschaeufele** [NVlabs/tiny-cuda-nn#24]
In line 150 of `samples/mlp_learning_an_image.cu` the following code is used to set the number of layers:
```
{"n_layers", 4},
```
However, this is ignored and the default is used instead, as the correct name for this option is `n_hidden_layers`. Also this doesn't give any warnings as unknown options are just ignored.

PS: A proper documentation for the config would be very nice, as currently it is necessary to look for the available options in the code. Also the possibility to print the used configuration would be helpful for debugging and avoiding errors like these.

**Comment by Tom94** [comment]
Good catch, thanks!

There is a documentation, actually. It's linked in the README: https://github.com/NVlabs/tiny-cuda-nn/blob/master/DOCUMENTATION.md

**Comment by danielschaeufele** [comment]
Thanks for the link, I should have read the readme more carefully :sweat:

**Comment by Tom94** [comment]
Addressed with https://github.com/NVlabs/tiny-cuda-nn/commit/8e1f4a247b9bcfad6f3849b2c09ebffa44b8640b :)

(Gonna keep track of the `to_json` todo separately. We should totally add it eventually.)
