### ISSUE TITLE
[bug?] sphere harmonics encoding's backward function

### ISSUE THREAD

**Issue by ashawkey** [NVlabs/tiny-cuda-nn#25]
Hi, 
In [this line](https://github.com/NVlabs/tiny-cuda-nn/blob/a77486c04ebc2973ec02fdbdea7c007948bf54cf/include/tiny-cuda-nn/encodings/spherical_harmonics.h#L158), `stride` is set to `sh_degree`, but shouldn't it be `sh_degree * sh_degree`?

**Comment by Tom94** [comment]
Thank you very for catching that, you're 100% correct. Fix incoming.

**Comment by Tom94** [comment]
Fixed by https://github.com/NVlabs/tiny-cuda-nn/commit/8575542682cb67cddfc748cc3d3cfc12593799aa

**Comment by ashawkey** [comment]
Got it, thanks for your quick reply!
