### ISSUE TITLE
source_files referenced before assignment (installation of torch bindings)

### ISSUE THREAD

**Issue by Morisander** [NVlabs/tiny-cuda-nn#255]
Good day my friends, 

i was trying to install nvdiffrec and followed the instructions (and found my mistakes and fixed them all) until i got to the point of installing tiny-cuda-nn or better said the in the instructions stated torch bindings.

as soon as i run the command 
pip install --global-option="--no-networks" git+https://github.com/NVlabs/tiny-cuda-nn#subdirectory=bindings/torch

it will give me the following error stating that the local variable "source_files" gets referenced before assignment.
at first look on the code i see no reason why this may happen, but hopefully someone here may get it and help me a little^^

error:
error: subprocess-exited-with-error

  × Running setup.py install for tinycudann did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      Building PyTorch extension for tiny-cuda-nn version 1.7
      Obtained compute capabilities [75] from environment variable TCNN_CUDA_ARCHITECTURES
      Building >> without << neural networks (just the input encodings)
      nvcc: NVIDIA (R) Cuda compiler driver
      Copyright (c) 2005-2021 NVIDIA Corporation
      Built on Fri_Dec_17_18:28:54_Pacific_Standard_Time_2021
      Cuda compilation tools, release 11.6, V11.6.55
      Build cuda_11.6.r11.6/compiler.30794723_0
      Detected CUDA version 11.6
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\dermo\AppData\Local\Temp\pip-req-build-24di1qez\bindings/torch\setup.py", line 173, in <module>
          ext_modules = [make_extension(comp) for comp in compute_capabilities]
        File "C:\Users\dermo\AppData\Local\Temp\pip-req-build-24di1qez\bindings/torch\setup.py", line 173, in <listcomp>
          ext_modules = [make_extension(comp) for comp in compute_capabilities]
        File "C:\Users\dermo\AppData\Local\Temp\pip-req-build-24di1qez\bindings/torch\setup.py", line 160, in make_extension
          sources=source_files,
      UnboundLocalError: local variable 'source_files' referenced before assignment
      [end of output]

**Comment by Tom94** [comment]
Hi, sorry about that, this seems to have regressed recently. I pushed a fix; could you try again?

**Comment by Morisander** [comment]
Yes, it just worked!^^ thanks a lot for this quick fix mate! you are a genius!
