### ISSUE TITLE
Understand matrix chunk loads to/from shared memory

### ISSUE THREAD

**Issue by kst179** [NVlabs/tiny-cuda-nn#257]
Hi! Nice work, it's a really great lib and NERFs in real time looks awesome =). But I wish to extend it a little bit. For that I am trying to understand how global memory copied to shared one in the sources of fully fused mlp. For example [here](https://github.com/NVlabs/tiny-cuda-nn/blob/master/src/fully_fused_mlp.cu#L146) the arrays of `__half`s are copied through `int4` representation, like that:

```C++
template<typename T>
__device__ copy(const T* in, T* out) {
    uint32_t i = threadIdx.x * sizeof(int4) / sizeof(T);
    *(int4*)&out[i] = *(int4*)&in[i];
}
```

So the question is **why there are no bank conflicts,** (or are there?) I mean we copy 4-sized structure (containing 4 32-bit words, one word can be accessed through one bank) and 4 threads in a warp (for example 0th, 8th, 16th, 24th) are trying to read (and then write) from (to) single bank simultaneously. As I understand It is somehow connected with the matrix skew, which is `16 = 8 * sizeof(__half) = 4 * sizeof(uint32_t)` bytes padding every `32 * N_BLOCKS = 16 * N_BLOCKS * sizeof(__half) = 8 * N_BLOCKS * sizeof(uint32_t)` bytes. But it looks like It would not save us from conflicts, because in terms of 32-bit words you should pad by 1, 3, 5 or other coprime with 32 each 32 (number of banks) elements, and skew is 4 32-bit words in which case conflicts are just shifted by one bank. I understand that using skew equal to 1 or 3 32-bit words would lead to the misalignment when addressing to the `int4` representation of array as well as when loading blocks of this chunk matrix to tensor core registers. But wouldn't it be faster to copy via `uint32_t`, two `__half`'s in one thread, and without bank conflicts?

I am new to CUDA, so maybe I just missed something about `int4` manipulations but I did not find everything specific about it in dev programming guide neither on the forums (it looks just like the usual structure of 4 ints, but i suppose there are some hardware optimizations of elementwise vector operations). Or maybe I just misunderstanding how shared banks are organised. Hope your answer shed the light to my understanding of how `int4` copy works and why you are using `skew=8` in shared memory chunks.

**Comment by kst179** [comment]
Ok, that makes a point, thank you for the quick answer!
But I still don't get the necessity of the skew, because if it has the same size as int4 (16 bytes) then when copying `.x` field of int4 simultaneously in all threads we use only banks with numbers **multiple of 4** and just skip one of the multipliers because of the skew (and then it repeats for `.y`, `.z` and `.w`). I showed it in example for WIDTH=16, for first 8 threads and there only "blue" banks used, which is corresponding to multiples of 4, and puncture arrows map to the skew, so we do not actually read or store this values: 

![banks conflict](https://user-images.githubusercontent.com/6316593/216037018-003a2488-19e9-41a0-b149-92c27958e335.png)

So how exactly skew should speed up the process? I have already made sure that without skew, benchmarks show almost 2 times worse performance, but still don't understand why.

**Comment by Tom94** [comment]
Ah, that's because the GPU has vector-load instructions of up to 128bit -- the int4 cast is used to encourage such vector-load instructions. The memory controller then loads the 4 adjacent words simultaneously. (Reality is slightly more complicated, because the memory controller can additionally "coalesce" multiple loads into a single one if neighboring threads access neighboring memory. But I am not sure about how much this is a factor here and haven't profiled with a focus on this.)

**Comment by kst179** [comment]
Yes, I understand it so that vector-load allows us to use 4 banks by one thread simultaneously, so all banks seems to be occupied. But still skew doesn't give us some profit here, we just skip 4 banks for no reason and just change the permutation of the accessing 4-bank-clusters from each thread but still each 4-banks-cluster occupied by 4 threads, so why not do that in a simple manner (`skew = 0`, `i`-th thread work with banks from `(i * 4) % 32` to `(i * 4) % 32 + 3`)?

**Comment by Tom94** [comment]
I should clarify is that the skew is not helping when copying memory linearly. So I wouldn't expect a speed-up in the `copy` function you mentioned at the top. It would be quite shocking if a common operation such as a memcopy needed such non-trivial code to be maximally efficient. :)

No, the skew avoids bank conflicts in the block-wise matrix multiply algorithm, where individual 16x16 blocks are read from (and written to) shared memory simultaneously by multiple threads/warps via `wmma::load_matrix_sync` (`wmma::store_matrix_sync`). While the exact mechanism of these functions is implementation-defined, it likely has a deterministic access pattern (e.g. reading 128-bit chunks of shmem in sequence, although I don't know for sure and am making an educated guess here) and the skew ensures that that access pattern is offset by a multiple of 4 banks w.r.t. each 16x16 block (assuming the width of the matrix is a power of 2 and the blocks being loaded are fewer than #banks/4 blocks apart).

**Comment by kst179** [comment]
Aaahhh, I see, I was convinced that skew is needed in data loading and store (from global memory not tensor core registers). Just because I have seen nothing in developer guide about what stride should be in tensor core operations (only that pointer should be 256 bit aligned and stride also should be multiple of 256 bits). So you reverse-engineered the __unspecified__ load/store and get some additional performance from that, that's very cool =)

I have finally come to the understanding of how fully fused mlp works (at least the forward part). But it seems that skew is not needed only if WIDTH=16, because there is no problem with side blocks which occupies the half or even 3/4 of banks. But yes, in that case there not too much shared memory used and I suppose 16-wide network is too thin for real use, so anyway skew does not add some problems =)

Thank you for your help, It was extremely useful for me!
