### ISSUE TITLE
deep copy of GPUMatrix

### ISSUE THREAD

**Issue by no-Seaweed** [NVlabs/tiny-cuda-nn#274]
Hi there,

Currently, I am developing a new nerf-based algorithm based on tcnn and instant-ngp. For my use case, I need to input two pairs of inputs into inference_mixed_precision method. To avoid changing all inference_mixed_precision methods with two split input parameters, I concatenate my inputs together into a single GPUMatrix. Thus, in the inference_mixed_precision_impl method, I expect to do slice and resize on the input GPUMatrix. The problem is that the input variable is set with const, and I could not directly modify the input shape. In this way, what I am trying to do is to do a deepcopy on the input GPUMatrix into a new one like so
`
void inference_mixed_precision_impl(cudaStream_t stream, const tcnn::GPUMatrixDynamic<float>&input, ...) override {
tcnn:GPUMatrixDynamic<float>& input_copy = GPUMatrixDynamic<float>{(float*)input.data(), input.m(), input.n(), input.layout()};
...
}
`
Is this a correct way to deepcopy the GPUMatrix?
I am greenhand on CUDA programming. Would this slow down the entire process? If so, is there any suggestion to better achieve the goal of my use case?

Best,
S.F.

**Comment by Tom94** [comment]
Hi, this sounds to me like your use case doesn't actually demand a deep copy, but a slice of the concatenated matrix. To this end simply use
```cpp
auto sliced_matrix = input.slice_cols(offset, size);
```
In general, I recommend checking out `gpu_matrix.h` to see the API of the `GPUMatrix*` classes.
