### ISSUE TITLE
OSError: Could not find compatible tinycudann extension for compute capability 75.

### ISSUE THREAD

**Issue by j93hahn** [NVlabs/tiny-cuda-nn#285]
This is a similar problem referenced here https://github.com/NVlabs/tiny-cuda-nn/issues/245. I am running into the error message: `OSError: Could not find compatible tinycudann extension for compute capability 75.`

Hardware:
OS: CentOS Linux
CUDA: 11.7
PyTorch: 1.12.1
NVIDIA-Driver: 515.57

I am able to install tiny-cuda-nn as part of nerfstudio on another graphics card but when I run an interactive job on this one I am getting this compute capability error. Should I just install CUDA 11.8 directly to the graphics card? I am not entirely sure if that's possible, or if there is a fix that can be solved via environment tweaking.

**Comment by LKyra** [comment]
Maybe you can install version 1.6 of tinnycudann. I solved the same error as you through this method.

**Comment by j93hahn** [comment]
solved - upgraded graphics card to cuda 12.0

**Comment by lishu2006ll** [comment]
I am running into the error message: OSError: Could not find compatible tinycudann extension for compute capability 75.

Hardware:
OS: win10
CUDA: 11.8
torch              2.0.0+cu118
torchaudio         2.0.1+cu118
torchvision        0.15.1+cu118
 NVIDIA-SMI 531.14                 Driver Version: 531.14       CUDA Version: 12.1
