### ISSUE TITLE
Difference between allocate_workspace_and_distribute and GPUMatrixDynamic

### ISSUE THREAD

**Issue by jc211** [NVlabs/tiny-cuda-nn#292]
Hey @Tom94 ,

Is there a performance difference between temporarily creating gpu memory using:

```cpp
tcnn::GPUMatrixDynamic<uint32_t> temp(num_elements, 1, stream);
```

and 

```cpp
auto scratch = tcnn::allocate_workspace_and_distribute<uint32_t>(stream, &alloc, num_elements); 
uint32_t temp = std::get<0>(scratch);
```

Is the first just a wrapper around the second?

**Comment by Tom94** [comment]
Hi, yes, `GPUMatrix(..., stream)` (and the dynamically laid out one) use the same GPU memory arenas under the hood and tie the allocation's lifetime to the matrix.

There is also a third, simpler option if you just want a set number of bytes:
```c++
GPUMemoryArena::Allocation scratch = tcnn::allocate_workspace(stream, n_bytes);
uint8_t* bytes = scratch.data(); // lives as long as `scratch` lives
```
