### ISSUE TITLE
Non-linearity Scaling

### ISSUE THREAD

**Issue by classner** [NVlabs/tiny-cuda-nn#296]
Hi!

I just ran into an issue using the Squareplus implementation in tiny-cuda-nn, which I traced back to its implementation [here](https://github.com/NVlabs/tiny-cuda-nn/blob/abb808d56bd021175a325bfa4cacc18a3555acee/include/tiny-cuda-nn/common_device.h#L114-L126).

As far as I understand, the intention is to scale the inputs using `K_ACT` and undo the scaling after applying the non-linearity (presumably for numerical stability?). However, since the function is non-linear, the scaling does not actually work as intended. Simple example for Squareplus with 0: squareplus(0) should be 1 by its formula (which is also mentioned in the documentation [here](https://github.com/NVlabs/tiny-cuda-nn/blob/master/DOCUMENTATION.md#activation-functions)), but is 1./10. computed by the tiny-cuda-nn activation. The same problem exists for Softplus.

**Comment by Tom94** [comment]
Hi, the behavior you observe is intended. The purpose of `K_ACT` is not numeric stability but to control how closely squareplus (and softplus for that matter) resemble a ReLU. For `K_ACT -> infinity`, these activations approach the ReLU. And for `K_ACT -> 0`, they become progressively smoother.

tiny-cuda-nn currently doesn't allow passing parameters to activation functions (for implementation reasons), which means we're stuck with a compile time constant -- and `K_ACT == 10` empirically worked much better than `K_ACT == 1` in the use cases I tried in the past.

**Comment by Tom94** [comment]
You're right that the docs should reflect this!

I'm fairly certain the derivatives are correct. Multiplying the input of a function by a constant and dividing the output by the same constant leaves derivatives unaffected (except that they need to be evaluated on a squished domain).
