### ISSUE TITLE
Frequency Encoding

### ISSUE THREAD

**Issue by classner** [NVlabs/tiny-cuda-nn#298]
Hi again! :) 

Just a quick question on the implementation of the frequency encoding: the documentation states that this is the version from Mildenhall et al., and right in the code [here](https://github.com/NVlabs/tiny-cuda-nn/blob/master/include/tiny-cuda-nn/encodings/frequency.h#L74-L80) this is reinforced, however the actual mapping multiplies the input with pi before going through the sine function. What is the reason for this change? Did you find a performance difference? Again, this would be good to mention in the code comment as well as [here](https://github.com/NVlabs/tiny-cuda-nn/blob/master/DOCUMENTATION.md#frequency).

* Implementation by Mildenhall et al.: https://github.com/bmild/nerf/blob/master/run_nerf_helpers.py#L48-L49 .
* nerf-pytorch: https://github.com/yenchenlin/nerf-pytorch/blob/63a5a630c9abd62b0f21c08703d0ac2ea7d4b9dd/run_nerf_helpers.py#L38

**Comment by Tom94** [comment]
Hi again indeed. This is a good catch, thanks!

Check out eq. 4 from the [NeRF paper](https://arxiv.org/pdf/2003.08934.pdf) which _does_ have the factor of pi in it. So... it seems that the official implementations don't quite match with their paper. But at the same time, they use different normalization schemes for their coordinates than, say, instant-ngp, brings back a factor of 2-3. So everything stays in a similar ballpark.

My experience with these logarithmically scaling encodings is that constant factors don't matter much -- if you're conservative and include enough frequencies to cover all practical scales in any case -- but I've clarified things in the docs and fixed the comment in `frequency.h` that you pointed out. That comment was a mess... it only lacked the factor of `pi` for the first term, but already had it for the others. It's shocking that it stayed like that for over a year. Again, thanks!

**Comment by classner** [comment]
Huh, good catch on your end w.r.t. the formula in the paper - I wonder what the story behind the implementation there is, maybe @tancik can comment on that? Agreed that it probably doesn’t play a big role, this was again more a concern for compatibility and documentation for interfacing with the library.

Thanks a lot for the quick response and the documentation updates!
