### ISSUE TITLE
Fused MLP

### ISSUE THREAD

**Issue by pure-water** [NVlabs/tiny-cuda-nn#31]
For the Fused MLP,  is it true the more layers are, the more benefits of the fused MLP can achieve?

**Comment by Tom94** [comment]
Yes, that's correct! The more layers there are, the bigger the proportion of cross-layer memory transfer that's accelerated by the fully fused approach. (Although, of course, the benefits are diminishing. The speedup approaches some constant, depending on your hardware.)
