### ISSUE TITLE
The output of Hashgrid is half nan

### ISSUE THREAD

**Issue by Net-Maker** [NVlabs/tiny-cuda-nn#318]
My input information:
```
dtype:torch.float32
shape:[65535,3]
```
I am sure that my input has no nan.
My encoding config:
```
	"encoding": {
		"otype": "HashGrid",
		"n_levels": 16,
		"n_features_per_level": 2, 
		"base_resolution": 16,
		"log2_hashmap_size": 19
	}
```
the output is half nan ,I have seen #219  and I think this is the same error due to the float-16 precision.
I saw the answer by @Tom94 ,which said :"use tcnn only for its encodings (which do support dtype=float32)."
so how could i solve this?

**Comment by Net-Maker** [comment]
reinstall tiny-cuda-nn works.
The real reason is i had modify the source code.And now I realize why my code got bad result.......

**Comment by HLJT** [comment]
Are you using HashGrid to encode three-dimensional points? I'm curious how you achieved it? Can I use tcnn.embed directly? Is there anything I need to change? I would be grateful if you could tell me.
