### ISSUE TITLE
About HashGrid Encoder's gradient with respect to the input position

### ISSUE THREAD

**Issue by ashawkey** [NVlabs/tiny-cuda-nn#32]
Hi, 
I wonder why [here](https://github.com/NVlabs/tiny-cuda-nn/blob/master/include/tiny-cuda-nn/encodings/grid.h#L225) the weight is set to `scale` instead of `1`? I don't see `scale` got involved in the forward computation.
Besides, is there any experiment or test that uses this input gradient currently?

**Comment by Tom94** [comment]
Hi there, the `scale` multiplication in the forward pass happens in the call to `pos_fract`.

**Comment by Tom94** [comment]
As for your second question: in __instant-ngp__, the derivatives w.r.t. input position are used in
- the analytic normals mode of SDF rendering (allows visual comparison with finite differences for debugging)
- the extrinsics / distortion optimization feature of NeRF, as well as
- the `ERenderMode::Normals` render mode of NeRF.

I think those are all usages, but I might misremember.

**Comment by ashawkey** [comment]
Thanks a lot for your answer! You are right, I missed that function.
