### ISSUE TITLE
Cannot create `Network` because tiny-cuda-nn was not compiled with neural network support.

### ISSUE THREAD

**Issue by BinglunWang** [NVlabs/tiny-cuda-nn#321]
Hi,

When I use tcnn.network in Colab. I always have this problem. Do u know how to fix it?

Thank you so much in advance.

**Comment by ruaruaruabick** [comment]
same problem

**Comment by Mkhuphy** [comment]
Use the following:
!pip install git+https://github.com/NVlabs/tiny-cuda-nn#subdirectory=bindings/torch
to install tiny-cuda-nn. Just remove the "--no-networks"
@isa

> Installing `tinycudann` without `--no-networks` option solves this issue for me.

works for me too
