### ISSUE TITLE
Why put grid offset table in constant cache?

### ISSUE THREAD

**Issue by wilsonCernWq** [NVlabs/tiny-cuda-nn#351]
May I know why this [commit](https://github.com/NVlabs/tiny-cuda-nn/commit/08e1c68db3c0f8444334269ac0849eaea354c9d4) was introduced? In my neural rendering application, I found that this single modification can lead to a sizable performance regression. So I am wondering the consideration behind this change.

Thank you.

**Comment by Tom94** [comment]
It's for multi-GPU use cases. Regular global memory needs to be allocated separately for each GPU and it was easier to move the hashgrid description to kernel parameters than to add an extra mechanism for multi-GPU-synced global memory.

In my own experiments, I could not measure a performance difference, so I'd appreciate if you could share more details. I had also tried managed memory (which automatically syncs itself to multiple GPUs), but found it quite a bit slower.

**Comment by wilsonCernWq** [comment]
I see, that makes sense, thank you very much.

Our application is about using implicit neural representation for scientific data compression and scientific visualization. In particular, it provides interactive volume ray marchers and volumetric path tracers that directly work on INR produced by TCNN. We developed two strategies for inferencing an INR: one is to write the rendering algorithm in a wavefront style and call TCNN API at the correct time; the other one is to have a megakernel renderer and extend TCNN to support in-shader inference. You can find more information about our project [here](https://github.com/VIDILabs/instantvnr).

So the issue happened with in-shader inference, where I have a encoder and network context wrapping parameters for each, and pass them around inside the kernel. Moving from TCNN v1.3-ish to v1.6 decreased our in-shader renderer's performance by 50%, and I narrowed it down to this commit.

However, after some more digings, I think the actual problem is I have some device functions receiving the encoder context by copy. Since the size of the encoder context now increased a lot, this becomes a quite expensive operation. It is an easy enough fix on my side to recover the performance, but I was just wondering why the change was necessary in the first place :D
