### ISSUE TITLE
ERROR: tiny-cuda-nn/dependencies/json/json.hpp:3954:14: fatal error: filesystem: No such file or directory

### ISSUE THREAD

**Issue by garrisonz** [NVlabs/tiny-cuda-nn#352]
System setting
ubuntu 20.04
g++ 9.4
cuda driver 470.57.02
cuda toolkit 11.4
torch 1.12.1

run
```
tiny-cuda-nn$ cd bindings/torch
tiny-cuda-nn/bindings/torch$ pip install .
```

Output many c++ ``No such file or directory` error, e.g.
```
tiny-cuda-nn/dependencies/json/json.hpp:3954:14: fatal error: filesystem: No such file or directory
           #include <filesystem>
                    ^~~~~~~~~~~~
      compilation terminated.
```

**Comment by garrisonz** [comment]
The default gcc / g++ version is 7.5. I only switch g++ to g++-9.
the installation and compilation of tiny-cuda-nn invokes g++ / gcc / c++ all. So, all of three should point to the same version (version 9). Then installation works fine.

**Comment by coollzd** [comment]
hi，I switched g++ and gcc to 9 but still failed, what can I do?
