### ISSUE TITLE
Help implementing 3D SDF/UDF fitting

### ISSUE THREAD

**Issue by lykius** [NVlabs/tiny-cuda-nn#36]
Hi,
This framework is really amazing, thanks a lot for sharing it.

I've been playing around with `samples/mlp_learning_an_image.cu` and I was wondering if it is possible to adapt it in order to fit a point cloud or a mesh by fitting its UDF/SDF.
I'm not really expert in CUDA programming, do you think it's doable with a reasonable effort? Do you have any suggestion?
I was thinking about computing coordinates and groundtruths in python and saving them in numpy files, then loading these numpy files inside the CUDA program (with cnpy). But after that, I'm not sure about the next steps. In the image case, you create a CUDA texture that seems quite specific for 2D images, how should I adapt it to 3D data?

Thanks in advance for any kind of help,
Luca

**Comment by Tom94** [comment]
Hi, absolutely! In our [__instant-ngp__ project](https://github.com/NVlabs/instant-ngp), we've implemented a number of neural graphics primitives using this framework, one of which is indeed an SDF. You can run it and pass it a `.obj`-formatted mesh and it'll fit a corresponding SDF within a second or so + give you a live rendering preview.

**Comment by lykius** [comment]
Hi @Tom94, thanks a lot for your answer!

I know `instant-ngp`, it's super awesome!! I was trying to use `tiny-cuda-nn` since I'm currently interested in a more general MLP formulation, without hash encoding. Maybe I can start from the SDF fitting in `instant-ngp` and remove the hash encoding. What do you think?

**Comment by Tom94** [comment]
__instant-ngp__'s SDF code uses __tiny-cuda-nn__'s `NetworkWithInputEncoding`, which can use any encoding that you'd like. All you need to do is change out the encoding in the `.json` configuration that you pass to the program via the `--network` argument. It loads `<task>/base.json` by default, where <task> is sdf in this case.

**Comment by lykius** [comment]
Ok I'll try that!
Thanks a lot, I really appreciate your help!

**Comment by Tom94** [comment]
Gladly!
