### ISSUE TITLE
Build failure on WSL with GCC 11.4.0

### ISSUE THREAD

**Issue by dannysbentley** [NVlabs/tiny-cuda-nn#366]
Hi there,

I've been trying to build Tiny-cuda-nn on WSL, but I'm running into some trouble. Here's a quick overview of my system:

- NVIDIA GPU: RTX 3090
- Compiler: GCC 11.4.0
- Operating System: Windows Subsystem For Linux
- CUDA version: 11.4
- CMake version v3.21 or higher

When running `make` after `cmake ..`, I encounter the following error:
/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’: 435 | function(_Functor&& __f) |
/usr/include/c++/11/bits/std_function.h:435:145: note: ‘_ArgTypes’ /usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’: 530 | operator=(_Functor&& __f) | ^ /usr/include/c++/11/bits/std_function.h:530:146: note: ‘_ArgTypes’

This error seems to point to a compatibility problem between the GCC version I'm using and Tiny-cuda-nn.

I've already tried several modifications to the `CMakeLists.txt` based on advice from an OpenAI developer, including setting `CMAKE_CXX_STANDARD` to `11` and adding `target_compile_features(tiny-cuda-nn PRIVATE cuda_std_11)`. However, the issue is persisting.

Could you help me find a way to get past this step? Please let me know if there is additional information you need.

Thanks!

Danny Bentley

**Comment by rohit7044** [comment]
Can you please share how you fixed it?

**Comment by AntoBongio** [comment]
Same problem here, could you please share your solution? @dannysbentley
