### ISSUE TITLE
windows11 ERROR:Building wheel for tinycudann (setup.py) ... error

### ISSUE THREAD

**Issue by lichard001** [NVlabs/tiny-cuda-nn#403]
### > **Method 1：When I enter the command, I get these errors.**
> 
>  **pip install ninja git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch**

Collecting git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
  Cloning https://github.com/NVlabs/tiny-cuda-nn/ to c:\users\石头\appdata\local\temp\pip-req-build-zlk72sx0
  Running command git clone --filter=blob:none --quiet https://github.com/NVlabs/tiny-cuda-nn/ 'C:\Users\石头\AppData\Local\Temp\pip-req-build-zlk72sx0'
  Resolved https://github.com/NVlabs/tiny-cuda-nn/ to commit c12645dfbac707ccd82907a209edff9b258f1e3d
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... done
Collecting ninja
  Using cached ninja-1.11.1.1-py2.py3-none-win_amd64.whl.metadata (5.4 kB)
Using cached ninja-1.11.1.1-py2.py3-none-win_amd64.whl (312 kB)
Building wheels for collected packages: tinycudann
  Building wheel for tinycudann (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [45 lines of output]
      C:\Users\石头\AppData\Local\Temp\pip-req-build-zlk72sx0\bindings/torch\setup.py:5: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
        from pkg_resources import parse_version
      Building PyTorch extension for tiny-cuda-nn version 1.7
      Obtained compute capabilities [86] from environment variable TCNN_CUDA_ARCHITECTURES
      nvcc: NVIDIA (R) Cuda compiler driver
      Copyright (c) 2005-2022 NVIDIA Corporation
      Built on Wed_Sep_21_10:41:10_Pacific_Daylight_Time_2022
      Cuda compilation tools, release 11.8, V11.8.89
      Build cuda_11.8.r11.8/compiler.31833905_0
      Detected CUDA version 11.8
      Targeting C++ standard 17
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-38
      creating build\lib.win-amd64-cpython-38\tinycudann
      copying tinycudann\modules.py -> build\lib.win-amd64-cpython-38\tinycudann
      copying tinycudann\__init__.py -> build\lib.win-amd64-cpython-38\tinycudann
      running egg_info
      creating tinycudann.egg-info
      writing tinycudann.egg-info\PKG-INFO
      writing dependency_links to tinycudann.egg-info\dependency_links.txt
      writing top-level names to tinycudann.egg-info\top_level.txt
      writing manifest file 'tinycudann.egg-info\SOURCES.txt'
      reading manifest file 'tinycudann.egg-info\SOURCES.txt'
      writing manifest file 'tinycudann.egg-info\SOURCES.txt'
      copying tinycudann\bindings.cpp -> build\lib.win-amd64-cpython-38\tinycudann
      running build_ext
      building 'tinycudann_bindings._86_C' extension
      creating C:\Users\石头\AppData\Local\Temp\pip-req-build-zlk72sx0\bindings\torch\build\dependencies
      creating C:\Users\石头\AppData\Local\Temp\pip-req-build-zlk72sx0\bindings\torch\build\dependencies\fmt
      creating C:\Users\石头\AppData\Local\Temp\pip-req-build-zlk72sx0\bindings\torch\build\dependencies\fmt\src
      creating C:\Users\石头\AppData\Local\Temp\pip-req-build-zlk72sx0\bindings\torch\build\src
      creating C:\Users\石头\AppData\Local\Temp\pip-req-build-zlk72sx0\bindings\torch\build\temp.win-amd64-cpython-38
      creating C:\Users\石头\AppData\Local\Temp\pip-req-build-zlk72sx0\bindings\torch\build\temp.win-amd64-cpython-38\Release
      creating C:\Users\石头\AppData\Local\Temp\pip-req-build-zlk72sx0\bindings\torch\build\temp.win-amd64-cpython-38\Release\tinycudann
      Emitting ninja build file C:\Users\石头\AppData\Local\Temp\pip-req-build-zlk72sx0\bindings\torch\build\temp.win-amd64-cpython-38\Release\build.ninja...
      Compiling objects...
      Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
      1.11.0
      creating C:\Users\石头\AppData\Local\Temp\pip-req-build-zlk72sx0\bindings\torch\build\lib.win-amd64-cpython-38\tinycudann_bindings
      "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\HostX64\x64\link.exe" /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:D:\miniconda3\envs\nerfstudio\lib\site-packages\torch\lib "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\lib\x64" /LIBPATH:D:\miniconda3\envs\nerfstudio\libs /LIBPATH:D:\miniconda3\envs\nerfstudio /LIBPATH:D:\miniconda3\envs\nerfstudio\PCbuild\amd64 "/LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22621.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22621.0\\um\x64" cuda.lib c10.lib torch.lib torch_cpu.lib torch_python.lib cudart.lib c10_cuda.lib torch_cuda.lib /EXPORT:PyInit__86_C C:\Users\石头\AppData\Local\Temp\pip-req-build-zlk72sx0\bindings\torch\build\temp.win-amd64-cpython-38\Release\../../dependencies/fmt/src/format.obj C:\Users\石头\AppData\Local\Temp\pip-req-build-zlk72sx0\bindings\torch\build\temp.win-amd64-cpython-38\Release\../../dependencies/fmt/src/os.obj C:\Users\石头\AppData\Local\Temp\pip-req-build-zlk72sx0\bindings\torch\build\temp.win-amd64-cpython-38\Release\../../src/common_host.obj C:\Users\石头\AppData\Local\Temp\pip-req-build-zlk72sx0\bindings\torch\build\temp.win-amd64-cpython-38\Release\../../src/cpp_api.obj C:\Users\石头\AppData\Local\Temp\pip-req-build-zlk72sx0\bindings\torch\build\temp.win-amd64-cpython-38\Release\../../src/cutlass_mlp.obj C:\Users\石头\AppData\Local\Temp\pip-req-build-zlk72sx0\bindings\torch\build\temp.win-amd64-cpython-38\Release\../../src/encoding.obj C:\Users\石头\AppData\Local\Temp\pip-req-build-zlk72sx0\bindings\torch\build\temp.win-amd64-cpython-38\Release\../../src/fully_fused_mlp.obj C:\Users\石头\AppData\Local\Temp\pip-req-build-zlk72sx0\bindings\torch\build\temp.win-amd64-cpython-38\Release\../../src/network.obj C:\Users\石头\AppData\Local\Temp\pip-req-build-zlk72sx0\bindings\torch\build\temp.win-amd64-cpython-38\Release\../../src/object.obj C:\Users\石头\AppData\Local\Temp\pip-req-build-zlk72sx0\bindings\torch\build\temp.win-amd64-cpython-38\Release\tinycudann/bindings.obj /OUT:build\lib.win-amd64-cpython-38\tinycudann_bindings\_86_C.cp38-win_amd64.pyd /IMPLIB:C:\Users\石头\AppData\Local\Temp\pip-req-build-zlk72sx0\bindings\torch\build\temp.win-amd64-cpython-38\Release\../../dependencies/fmt/src\_86_C.cp38-win_amd64.lib
      LINK : fatal error LNK1181: 无法打开输入文件“C:\Users\石头\AppData\Local\Temp\pip-req-build-zlk72sx0\bindings\torch\build\temp.win-amd64-cpython-38\Release\..\..\dependencies\fmt\src\format.obj”
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX64\\x64\\link.exe' failed with exit code 1181
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tinycudann
  Running setup.py clean for tinycudann
Failed to build tinycudann
ERROR: Could not build wheels for tinycudann, which is required to install pyproject.toml-based projects

___________________________________________________________________________________________

###  **Method 2：When I downloaded the file aaa and installed it locally, I still encountered the error.**
> (nerfstudio) C:\Users\石头\tiny-cuda-nn-master\bindings\torch>python setup.py install

setup.py:5: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import parse_version
Building PyTorch extension for tiny-cuda-nn version 1.7
Obtained compute capabilities [86] from environment variable TCNN_CUDA_ARCHITECTURES
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:41:10_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
Detected CUDA version 11.8
Targeting C++ standard 17
running install
D:\miniconda3\envs\nerfstudio\lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
D:\miniconda3\envs\nerfstudio\lib\site-packages\setuptools\_distutils\cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
writing tinycudann.egg-info\PKG-INFO
writing dependency_links to tinycudann.egg-info\dependency_links.txt
writing top-level names to tinycudann.egg-info\top_level.txt
reading manifest file 'tinycudann.egg-info\SOURCES.txt'
writing manifest file 'tinycudann.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
building 'tinycudann_bindings._86_C' extension
Emitting ninja build file C:\Users\石头\tiny-cuda-nn-master\bindings\torch\build\temp.win-amd64-cpython-38\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
1.11.0
"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\HostX64\x64\link.exe" /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:D:\miniconda3\envs\nerfstudio\lib\site-packages\torch\lib "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\lib\x64" /LIBPATH:D:\miniconda3\envs\nerfstudio\libs /LIBPATH:D:\miniconda3\envs\nerfstudio /LIBPATH:D:\miniconda3\envs\nerfstudio\PCbuild\amd64 "/LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22621.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22621.0\\um\x64" cuda.lib c10.lib torch.lib torch_cpu.lib torch_python.lib cudart.lib c10_cuda.lib torch_cuda.lib /EXPORT:PyInit__86_C C:\Users\石头\tiny-cuda-nn-master\bindings\torch\build\temp.win-amd64-cpython-38\Release\../../dependencies/fmt/src/format.obj C:\Users\石头\tiny-cuda-nn-master\bindings\torch\build\temp.win-amd64-cpython-38\Release\../../dependencies/fmt/src/os.obj C:\Users\石头\tiny-cuda-nn-master\bindings\torch\build\temp.win-amd64-cpython-38\Release\../../src/common_host.obj C:\Users\石头\tiny-cuda-nn-master\bindings\torch\build\temp.win-amd64-cpython-38\Release\../../src/cpp_api.obj C:\Users\石头\tiny-cuda-nn-master\bindings\torch\build\temp.win-amd64-cpython-38\Release\../../src/cutlass_mlp.obj C:\Users\石头\tiny-cuda-nn-master\bindings\torch\build\temp.win-amd64-cpython-38\Release\../../src/encoding.obj C:\Users\石头\tiny-cuda-nn-master\bindings\torch\build\temp.win-amd64-cpython-38\Release\../../src/fully_fused_mlp.obj C:\Users\石头\tiny-cuda-nn-master\bindings\torch\build\temp.win-amd64-cpython-38\Release\../../src/network.obj C:\Users\石头\tiny-cuda-nn-master\bindings\torch\build\temp.win-amd64-cpython-38\Release\../../src/object.obj C:\Users\石头\tiny-cuda-nn-master\bindings\torch\build\temp.win-amd64-cpython-38\Release\tinycudann/bindings.obj /OUT:build\lib.win-amd64-cpython-38\tinycudann_bindings\_86_C.cp38-win_amd64.pyd /IMPLIB:C:\Users\石头\tiny-cuda-nn-master\bindings\torch\build\temp.win-amd64-cpython-38\Release\../../dependencies/fmt/src\_86_C.cp38-win_amd64.lib
LINK : fatal error LNK1181: 无法打开输入文件“C:\Users\石头\tiny-cuda-nn-master\bindings\torch\build\temp.win-amd64-cpython-38\Release\..\..\dependencies\fmt\src\format.obj”
error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX64\\x64\\link.exe' failed with exit code 1181

**

> ### Can someone please save me, I've been tossing this around for a week now and still haven't managed to install it, thanks for any help anyone can give me, much appreciated.

**

**Comment by DongChengdongHangZhou** [comment]
when I update my gcc version from 7 to 9, I can solve this problem and successfully install tinycudann

**Comment by lichard001** [comment]
> when I update my gcc version from 7 to 9, I can solve this problem and successfully install tinycudann

Thank you.

**Comment by tornado404** [comment]
> when I update my gcc version from 7 to 9, I can solve this problem and successfully install tinycudann

gcc version 13.1.0 (MinGW-W64 x86_64-msvcrt-posix-seh, built by Brecht Sanders)
still failed

**Comment by dletozeun** [comment]
Hello,

If this can help, I encountered this issue while having VS 2019 installed on Windows. Installing VS 2022 made the script select the latest build tools (VS 2022 ones) and it worked!

**Comment by Aishwary-Mahajan** [comment]
> when I update my gcc version from 7 to 9, I can solve this problem and successfully install tinycudann

How to do this for conda environment in windows 11?
