### ISSUE TITLE
pip install:g++ error

### ISSUE THREAD

**Issue by Tracy-coder** [NVlabs/tiny-cuda-nn#432]
When I use the command `pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch` to install tinycudann in conda environment,an error occurs:

      g++: error: /tmp/pip-req-build-d19bf2m6/bindings/torch/build/temp.linux-x86_64-cpython-38/../../dependencies/fmt/src/format.o: No such file or directory
      g++: error: /tmp/pip-req-build-d19bf2m6/bindings/torch/build/temp.linux-x86_64-cpython-38/../../dependencies/fmt/src/os.o: No such file or directory
      g++: error: /tmp/pip-req-build-d19bf2m6/bindings/torch/build/temp.linux-x86_64-cpython-38/../../src/common_host.o: No such file or directory
      g++: error: /tmp/pip-req-build-d19bf2m6/bindings/torch/build/temp.linux-x86_64-cpython-38/../../src/cpp_api.o: No such file or directory
      g++: error: /tmp/pip-req-build-d19bf2m6/bindings/torch/build/temp.linux-x86_64-cpython-38/../../src/cutlass_mlp.o: No such file or directory
      g++: error: /tmp/pip-req-build-d19bf2m6/bindings/torch/build/temp.linux-x86_64-cpython-38/../../src/encoding.o: No such file or directory
      g++: error: /tmp/pip-req-build-d19bf2m6/bindings/torch/build/temp.linux-x86_64-cpython-38/../../src/fully_fused_mlp.o: No such file or directory
      g++: error: /tmp/pip-req-build-d19bf2m6/bindings/torch/build/temp.linux-x86_64-cpython-38/../../src/network.o: No such file or directory
      g++: error: /tmp/pip-req-build-d19bf2m6/bindings/torch/build/temp.linux-x86_64-cpython-38/../../src/object.o: No such file or directory
      g++: error: /tmp/pip-req-build-d19bf2m6/bindings/torch/build/temp.linux-x86_64-cpython-38/tinycudann/bindings.o: No such file or directory
      error: command '/usr/bin/g++' failed with exit code 1

info of my device:
g++-9
cmake version 3.29.3
torch==1.12.0+cu113
CUDA Version: 11.2

**Comment by aradhyamathur** [comment]
what does g++ --version return ?

**Comment by leviome** [comment]
1.
```
git clone --recursive https://github.com/nvlabs/tiny-cuda-nn
```
don't miss "--recursive"

2.
```
cd tiny-cuda-nn
python setup.py install
```
if fails, please
3.
```
cd buildbuild/temp.linux-x86_64-cpython-38
ninja -f build.ninja
cd ../..
python setup.py install
```

these steps solve my case.

**Comment by 411066282** [comment]
> ```
> git clone --recursive https://github.com/nvlabs/tiny-cuda-nn
> ```
> 
> don't miss "--recursive"
> 
> 
> ```
> cd tiny-cuda-nn
> python setup.py install
> ```
> 
> if fails, please 3.
> 
> ```
> cd buildbuild/temp.linux-x86_64-cpython-38
> ninja -f build.ninja
> cd ../..
> python setup.py install
> ```
> 
> these steps solve my case.

where is setup.py?
