### ISSUE TITLE
OSError: Could not find compatible tinycudann extension for compute capability 87.

### ISSUE THREAD

**Issue by Livioni** [NVlabs/tiny-cuda-nn#434]
Problems about running tinycudann on Jetson AGX Orin

Platform info:
![jtop](https://github.com/NVlabs/tiny-cuda-nn/assets/52649461/ff0bfc06-1733-4d24-bbc1-ca5c2c2ff66f)

torch 2.2.0
torchvision 0.17

Problem:
The following error occurs whenever I import tinycudann.

```bash
>>> import tinycudann
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xns/miniconda3/envs/3dgs/lib/python3.10/site-packages/tinycudann-1.7-py3.10-linux-aarch64.egg/tinycudann/__init__.py", line 9, in <module>
    from tinycudann.modules import free_temporary_memory, NetworkWithInputEncoding, Network, Encoding
  File "/home/xns/miniconda3/envs/3dgs/lib/python3.10/site-packages/tinycudann-1.7-py3.10-linux-aarch64.egg/tinycudann/modules.py", line 59, in <module>
    raise EnvironmentError(f"Could not find compatible tinycudann extension for compute capability {system_compute_capability}.")
OSError: Could not find compatible tinycudann extension for compute capability 87.
```

**Comment by Livioni** [comment]
I managed to resolve it by rebuiling tinycudann, the key step is to `export TCNN_CUDA_ARCHITECTURES=86`  before intalling PyTorch extension. 

I think tinycudann dose not support Jetson AGX Orin yet, because the jetson's cuda capability (87) is not in the supported list https://github.com/NVlabs/tiny-cuda-nn/blob/2ec562e853e6f482b5d09168705205f46358fb39/bindings/torch/tinycudann/modules.py#L16


``` bash
import tinycudann
/home/xns/miniconda3/envs/3dgs/lib/python3.10/site-packages/tinycudann-1.7-py3.10-linux-aarch64.egg/tinycudann/modules.py:53: UserWarning: tinycudann was built for lower compute capability (86) than the system's (87). Performance may be suboptimal.
  warnings.warn(f"tinycudann was built for lower compute capability ({cc}) than the system's ({system_compute_capability}). Performance may be suboptimal.")
```

**Comment by yhaddouda** [comment]
Hello, 
I have the same problem on my jetson orin, do you install tinycudann before instaling pytorch then? and can you elaborate in which step exactly you do : export TCNN_CUDA_ARCHITECTURES=86 ?
Thank you

**Comment by Tom94** [comment]
Hopefully this workaround is no longer needed. I just pushed an attempted fix that should make it work out of the box (see also https://github.com/NVlabs/tiny-cuda-nn/issues/436). Please try re-downloading and installing again -- could you let me know if it works?

**Comment by Livioni** [comment]
> Hopefully this workaround is no longer needed. I just pushed an attempted fix that should make it work out of the box (see also #436). Please try re-downloading and installing again -- could you let me know if it works?

Thanks for your reply, I will check it later！

**Comment by Livioni** [comment]
It works well now。

> > Hopefully this workaround is no longer needed. I just pushed an attempted fix that should make it work out of the box (see also #436). Please try re-downloading and installing again -- could you let me know if it works?
> 
> Thanks for your reply, I will check it later！
