### ISSUE TITLE
compute compatibility 87 ( jetson orin)

### ISSUE THREAD

**Issue by yhaddouda** [NVlabs/tiny-cuda-nn#436]
Hello,
I built tiny cuda nn from source using this repo to, run nerfacto on a jetson orin ( jetpack 6.0dp, cuda 12.2, python 3.10).
When compiling I get : OSError: Could not find compatible tinycudann extension for compute capability 87.
I don't know if this compute is compatible with tiny-cuda-nn as it is today ?

**Comment by Tom94** [comment]
Hi, I just pushed an attempted fix. Could you try to re-download and install?

**Comment by yhaddouda** [comment]
Hi, I re-downloaded the repo and got the same error as before.

**Comment by Tom94** [comment]
Could you paste the full log of the installation / compilation? Thanks!

**Comment by yhaddouda** [comment]
this is the cmake.log file:
-- Obtained CUDA architectures automatically from installed GPUs
-- Targeting CUDA architectures: 87
-- Module support is disabled.
-- Version: 9.1.1
-- Build type: RelWithDebInfo
-- Configuring done
-- Generating done
-- Build files have been written to: /home/nvidia/work/tiny-cuda-nn/build
and this is the build.log file:
Consolidate compiler generated dependencies of target fmt
[ 15%] Built target fmt
Consolidate compiler generated dependencies of target tiny-cuda-nn
[ 70%] Built target tiny-cuda-nn
Consolidate compiler generated dependencies of target mlp_learning_an_image
Consolidate compiler generated dependencies of target bench_image_ours
[ 90%] Built target mlp_learning_an_image
[100%] Built target bench_image_ours

thanks!

**Comment by Tom94** [comment]
That should work, actually. Any chance the previous (broken) version of tiny-cuda-nn wasn't uninstalled from pip before attempting the rerun? ```pip uninstall tinycudann``` followed by re-running ```pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch``` or ```python setup.py install``` (depending on your method of installation) should do the trick.

**Comment by yhaddouda** [comment]
Hello, thank you for you help. Indeed the library is working now, I just didn't do the uninstal step.
Thanks !
