### ISSUE TITLE
Does sample code with one-blob encoding still work?

### ISSUE THREAD

**Issue by shocker-0x15** [NVlabs/tiny-cuda-nn#46]
Thanks for sharing the great library.

I tried the sample code using the image in the data directory and have confirmed the program instantly learns the image with `"HashGrid"` encoding (config_hash.json). However, with one-blob encoding (config_oneblob.json), the program constantly produces completely black images.

I tried bisection to find with which revision this issue occurred and it seems `c88c1dcf81d89e0b4217ae4aaac34c963bf29d86` (The first revision for v1.2).

Does the sample with one-blob encoding still work in other environments other than me?

My environment:
Windows 10 21H2 (19044.1526)
Visual Studio Community 2022 (17.1.0)
cmake 3.21.4
RTX 3080 10GB
CUDA 11.6
Driver: 511.79

Thanks,

**Comment by Tom94** [comment]
Hi there, thanks for reporting this!

While everything works on my machine (Windows, WSL2, as well as native Linux), other users reported similar issues in the past.

[There's a (seemingly unrelated) fix to this problem](https://github.com/NVlabs/tiny-cuda-nn/commit/1e235e8b03acb220d8388dde5247f443621ba368) -- I suspect something funky in the underlying codegen -- which in the past always lead to slightly worse performance in the case of 128-neurons wide neural network.

But, and this stumps me, the fix in question _improved_ performance by ~10% when I tried it just now! I'm not going to question it and merely ask you to pull latest master to confirm it works now.

**Comment by shocker-0x15** [comment]
Wow, thanks for your quick response!
I pulled the latest master `1e235e8b03acb220d8388dde5247f443621ba368` and have confirmed it works perfectly with one-blob encoding.

I appreciate your quick fix.
