### ISSUE TITLE
why use a loss_scale ?

### ISSUE THREAD

**Issue by brabbitdousha** [NVlabs/tiny-cuda-nn#472]
When computing the gradient, it is multiplied by loss_scale = 128.0, but during the adam->step(), the gradient is divided by loss_scale. Why do we use loss_scale in the first place?

**Comment by Tom94** [comment]
It's for numeric precision when using FP16 floating point numbers. See https://docs.nvidia.com/deeplearning/performance/mixed-precision-training/index.html
