### ISSUE TITLE
Compilation error when building bindings/torch

### ISSUE THREAD

**Issue by theponpon** [NVlabs/tiny-cuda-nn#48]
Hi there,
First thanks for the really cool lib

When I try to build the torch bindings, I get the following error:

/mnt/DeepDrive/Projects/tiny-cuda-nn/src/fully_fused_mlp.cu(416): error: explicit type is missing ("int" assumed)

/mnt/DeepDrive/Projects/tiny-cuda-nn/src/fully_fused_mlp.cu(416): error: expected a ")"

/mnt/DeepDrive/Projects/tiny-cuda-nn/src/fully_fused_mlp.cu(496): error: explicit type is missing ("int" assumed)

/mnt/DeepDrive/Projects/tiny-cuda-nn/src/fully_fused_mlp.cu(496): error: expected a ")"

FAILED: /mnt/DeepDrive/Projects/tiny-cuda-nn/bindings/torch/src/fully_fused_mlp.o 
/home/pierre/anaconda3/envs/torch-ngp/bin/nvcc  -I/mnt/DeepDrive/Projects/tiny-cuda-nn/include -I/mnt/DeepDrive/Projects/tiny-cuda-nn/dependencies -I/home/pierre/anaconda3/envs/torch-ngp/lib/python3.8/site-packages/torch/include -I/home/pierre/anaconda3/envs/torch-ngp/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/pierre/anaconda3/envs/torch-ngp/lib/python3.8/site-packages/torch/include/TH -I/home/pierre/anaconda3/envs/torch-ngp/lib/python3.8/site-packages/torch/include/THC -I/home/pierre/anaconda3/envs/torch-ngp/include -I/home/pierre/anaconda3/envs/torch-ngp/include/python3.8 -c -c /mnt/DeepDrive/Projects/tiny-cuda-nn/src/fully_fused_mlp.cu -o /mnt/DeepDrive/Projects/tiny-cuda-nn/bindings/torch/src/fully_fused_mlp.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -std=c++14 --extended-lambda --expt-relaxed-constexpr -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -Xcompiler=-mf16c -Xcompiler=-Wno-float-conversion -Xcompiler=-fno-strict-aliasing -DTCNN_MIN_GPU_ARCH=61 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61

Configuration:
ubuntu 18.04
NVidia GeForce 1080ti
Driver Version 470.103.01
cuda 11.3.1
torch 10.2

Note: I have tried solution given in https://github.com/NVlabs/tiny-cuda-nn/issues/45 but it does not seem to work

Thanks in advance,

Pierre

**Comment by MoyGcc** [comment]
Almost the same problem here.

My configuration:
ubuntu 18.04
NVidia TITAN X
Driver Version 510.47.03
cuda 11.6
torch 1.8.1

Would really appreciate if someone can help!

**Comment by Tom94** [comment]
Hi there, could you try pulling the latest master and compiling again? I believe your issue got fixed by https://github.com/NVlabs/tiny-cuda-nn/commit/fb8f845ef4866f7f9610129389cd2f77ea9d2502
