### ISSUE TITLE
Problems running PyTorch bidings

### ISSUE THREAD

**Issue by danperazzo** [NVlabs/tiny-cuda-nn#49]
Hello everyone, thank you for sharing this great technique! I have been having problems building the Python bidings from source.
I tried running the command with `python setup.py install`, however, I got the following error message: [error_log.txt](https://github.com/NVlabs/tiny-cuda-nn/files/8118911/error_log.txt).

My system setup is as follows:
Windows 10
GTX 1060
CUDA 11.3
Visual Studio 2019
Cmake 3.22.1
PyTorch 1.10.2

Thanks for the attention :)

**Comment by Tom94** [comment]
These errors look like a mismatch between the installed visual studio and CUDA version -- unfortunately, there are frequent breaking changes between the two.

I recommend updating Visual Studio 2019 through the VS installer, _afterwards_ installing the latest CUDA 11.6, rebooting, and then trying again. Fingers crossed!

**Comment by danperazzo** [comment]
Did not work :/

**Comment by danperazzo** [comment]
To provide an update, updating the Visual Studio 2019 broke my installation of tiny-cuda-nn :/ I don't know if there is a problem with the incompatibility.

**Comment by danperazzo** [comment]
I managed to install the Python bindings! Here are the configurations I used:

Windows 10
GTX 1060
CUDA 11.6.1
Visual Studio 2019 (using the CXX compiler MSVC 19.29.30140.0)
Cmake 3.22.1
PyTorch 1.10.2 (installed with conda with cudatoolkit 11.3)

Initially, when I installed the python bindings (running `python setup.py install` , I got the following error:

```
fully_fused_mlp.cu
C:\Users\Temp\Desktop\3d-object-stationary-camera-implicit\code_c\tiny-cuda-nn\src\fully_fused_mlp.cu(415): error: name followed by "::" must be a class or namespace name

C:\Users\Temp\Desktop\3d-object-stationary-camera-implicit\code_c\tiny-cuda-nn\src\fully_fused_mlp.cu(493): error: name followed by "::" must be a class or namespace name

C:\Users\Temp\Desktop\3d-object-stationary-camera-implicit\code_c\tiny-cuda-nn\src\fully_fused_mlp.cu(493): error: name followed by "::" must be a class or namespace name

3 errors detected in the compilation of "../../src/fully_fused_mlp.cu".
error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.6\\bin\\nvcc.exe' failed with exit status 1
```

However, since my GPU does not have so much memory, I removed the FullyFused from my installation (it would not work anyway). Doing this ensured the instalation weny smoothly

**Comment by Tom94** [comment]
This is a really good catch, thank you! I pushed a fix to `setup.py` that won't include fully fused MLPs on older architectures where compilation would fail.

(CMake already does this, but I had forgotten to replicate the behavior in Python.)
