### ISSUE TITLE
RuntimeError: trying to differentiate twice a function that was markedwith @once_differentiable

### ISSUE THREAD

**Issue by theFilipko** [NVlabs/tiny-cuda-nn#50]
I am trying to use only the Encoding models for my SDF model, where the SDF network is written in pytorch. I need to calculate the gradients from the SDF network which goes as input to the Color network. However, when calling `loss.backward()` it says `RuntimeError: trying to differentiate twice a function that was markedwith @once_differentiable`. Any ideas how to solve it?

**Comment by Tom94** [comment]
__tiny-cuda-nn__ doesn't support second order derivatives, which means that the surface normal of the SDF network (which is the first derivative) is not allowed to appear anywhere in the loss. Or, alternatively, if it does appear, it must be computed in terms of finite differences such that everything boils down to just first-order derivatives.
