### ISSUE TITLE
Complie PyTorch Bindings with float32 precision.

### ISSUE THREAD

**Issue by srxdev0619** [NVlabs/tiny-cuda-nn#51]
Hi,

First up, thanks for this is great work! I was just wondering if there's a way to compile `tiny-cuda-nn` and its pytorch bindings to use `float32` by default? Thanks!

**Comment by Tom94** [comment]
Hi there, you can go into `include/tiny-cuda-nn/common.h` and change

```cpp
using network_precision_t = std::conditional_t<TCNN_HALF_PRECISION, __half, float>;
```

to 

```cpp
using network_precision_t = float;
```

Cheers!

**Comment by srxdev0619** [comment]
Worked perfectly, thanks!
