### ISSUE TITLE
Max Level - Grid Encoding

### ISSUE THREAD

**Issue by jc211** [NVlabs/tiny-cuda-nn#53]
I don't understand why max_level is being multiplied here. 
https://github.com/NVlabs/tiny-cuda-nn/blob/5c008099375de870eb3fdccdd3ba1c678fb89018/include/tiny-cuda-nn/encodings/grid.h#L158

This is effectively saying ` max_level *= n_levels ` and its not clear why it must be so. I also assume that max_level_gpu is some kind of fine grained control over a "per entry" max_level.

**Comment by Tom94** [comment]
The max level argument is expected to have the range [0, 1], where 1 means highest available and 0 means none. (The calling code has no way to know how many levels there actually exist.)

Admittedly, this could be made clearer by renaming the variables.

The conversion here transforms the range [0, 1] to [0, n_levels].
