### ISSUE TITLE
Loading and saving weights of pytorch wrapper of tiny-cuda-nn 

### ISSUE THREAD

**Issue by subinKim14** [NVlabs/tiny-cuda-nn#56]
Hi! I'm very excited by TinyCUDA implemented in pytorch version. 
I'd like to test it out for an inference task on a pre-trained model. 
How can I save the weight of trained model in python?
Also, how can I load the weight of pre-trained model from the saved weight file?

Do you have any advice on how I could go about accomplishing this?

Thanks :)

**Comment by Tom94** [comment]
For the pytorch bindings, this should work out-of-the-box with [`torch.save` and `torch.load`](https://pytorch.org/tutorials/beginner/saving_loading_models.html).
