### ISSUE TITLE
Horizontal wrapping hash grid?

### ISSUE THREAD

**Issue by jonathanventura** [NVlabs/tiny-cuda-nn#67]
How difficult would it be to make the HashGrid wrap horizontally?  This would be useful for representing panoramic scenes with a NeRF.

**Comment by Tom94** [comment]
Fairly simple -- I reckon it's sufficient to add the appropriate modulus to the `grid_index` function.

That said, I haven't experienced particularly visible seams without wrapping -- the interpolation doesn't cross the boundaries of the unit cube in any case, and the coinciding vertices on the boundary tend to lern similar values.
