### ISSUE TITLE
compile error in win10 with vs2019.16.11 and cuda 11.0

### ISSUE THREAD

**Issue by YK-hastur** [NVlabs/tiny-cuda-nn#74]
[E:\cv\instant-ngp-master\build\dependencies\tiny-cuda-nn\src\tiny-cuda-nn.vcxproj]
E:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\include\xmemory(309): error
: no operator "+" matches these operands [E:\cv\instant-ngp-master\build\dependencies\tiny-cuda-nn\src\tiny-cuda-nn.vcx
proj]

E:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\include\xmemory(919): error
: expected a "(" [E:\cv\instant-ngp-master\build\dependencies\tiny-cuda-nn\src\tiny-cuda-nn.vcxproj]

**Comment by yaohusama** [comment]
I have that problem,too.

**Comment by YK-hastur** [comment]
@yaohusama I found the reason, caused by the mismatch between the version of visual studio and CUDA, complie success when I change version to vs2019.16.11 and cuda 11.4

**Comment by Tom94** [comment]
That's good to know, thanks.

Unfortunately, this is hard, if not impossible, to fix on tiny-cuda-nn's end. Some versions of CUDA and visual studio are simply incompatible -- to the point where one should generally update both at the same time.

**Comment by hzhshok** [comment]
Hello, 
Now i have the same issue after i turn to torch to use this tiny-cuda-nn, so, can i make a request to reopen this issue to let someone give a help to support pytorch?  because, now pytorch stable only supports cuda11.3, THKS!

Or could i make a new issue?

Thanks very much for your help!

Regards
