### ISSUE TITLE
compile error in win10 with vs2019.16.11 and cuda 11.3

### ISSUE THREAD

**Issue by hzhshok** [NVlabs/tiny-cuda-nn#76]
Hello, 
Now i have the same issue with [#74](https://github.com/NVlabs/tiny-cuda-nn/issues/74), but i used vs2019.16.11 and cuda 11.3, but i saw the compile error is the same, so could you someone give a help to check that.

Hardware: GEFORCE RTX 3090
DRIVER: 472.84
CUDA: 11.3
VS: 2019.16.11.11
windows 10 SDK: 10.0.19041.0

In addition, why i used cuda11.3 is because the stable torch is only supporting cuda11.3 to compile binding/torch.

Error log:
 Compiling CUDA source file ..\..\src\common_device.cu...
  Compiling CUDA source file ..\..\src\common.cu...
  Compiling CUDA source file ..\..\src\cpp_api.cu...
  Compiling CUDA source file ..\..\src\encoding.cu...
  Compiling CUDA source file ..\..\src\cutlass_mlp.cu...
  Compiling CUDA source file ..\..\src\object.cu...
  Compiling CUDA source file ..\..\src\reduce_sum.cu...
  Compiling CUDA source file ..\..\src\loss.cu...
  Compiling CUDA source file ..\..\src\network.cu...
  Compiling CUDA source file ..\..\src\optimizer.cu...
  
  E:\Zhansheng\software\installed\tiny-cuda-nn\build\src>"E:\Zhansheng\software\installed\NVDIA-GPU-computing-toolkit\CUDA\v11.3\bin\nvcc.exe" -gencode=arch=compute_86,code=\"compute_86,compute_86\" -gencode=arch=compute_86,code=\"sm_86,compute_86\" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64" -x cu   -I"E:\Zhansheng\software\installed\tiny-cuda-nn\include" -I"E:\Zhansheng\software\installed\tiny-cuda-nn\dependencies" -I"E:\Zhansheng\software\installed\tiny-cuda-nn\dependencies\cutlass\include" -I"E:\Zhansheng\software\installed\tiny-cuda-nn\dependencies\cutlass\tools\util\include" -I"E:\Zhansheng\software\installed\NVDIA-GPU-computing-toolkit\CUDA\v11.3\include"     --keep-dir x64\RelWithDebInfo  -maxrregcount=0  --machine 64 --compile -cudart static --extended-lambda --expt-relaxed-constexpr -std=c++14 -Xcompiler="/EHsc -Zi -Ob1"   -D_WINDOWS -DNDEBUG -DTCNN_MIN_GPU_ARCH=86 -DTCNN_SHAMPOO -D"CMAKE_INTDIR=\"RelWithDebInfo\"" -D_MBCS -D"CMAKE_INTDIR=\"RelWithDebInfo\"" -Xcompiler "/EHsc /W1 /nologo /O2 /FdE:\Zhansheng\software\installed\tiny-cuda-nn\build\src\RelWithDebInfo\tiny-cuda-nn.pdb /FS /Zi  /MD /GR" -o tiny-cuda-nn.dir\RelWithDebInfo\common.obj "E:\Zhansheng\software\installed\tiny-cuda-nn\src\common.cu" 
  
  E:\Zhansheng\software\installed\tiny-cuda-nn\build\src>"E:\Zhansheng\software\installed\NVDIA-GPU-computing-toolkit\CUDA\v11.3\bin\nvcc.exe" -gencode=arch=compute_86,code=\"compute_86,compute_86\" -gencode=arch=compute_86,code=\"sm_86,compute_86\" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64" -x cu   -I"E:\Zhansheng\software\installed\tiny-cuda-nn\include" -I"E:\Zhansheng\software\installed\tiny-cuda-nn\dependencies" -I"E:\Zhansheng\software\installed\tiny-cuda-nn\dependencies\cutlass\include" -I"E:\Zhansheng\software\installed\tiny-cuda-nn\dependencies\cutlass\tools\util\include" -I"E:\Zhansheng\software\installed\NVDIA-GPU-computing-toolkit\CUDA\v11.3\include"     --keep-dir x64\RelWithDebInfo  -maxrregcount=0  --machine 64 --compile -cudart static --extended-lambda --expt-relaxed-constexpr -std=c++14 -Xcompiler="/EHsc -Zi -Ob1"   -D_WINDOWS -DNDEBUG -DTCNN_MIN_GPU_ARCH=86 -DTCNN_SHAMPOO -D"CMAKE_INTDIR=\"RelWithDebInfo\"" -D_MBCS -D"CMAKE_INTDIR=\"RelWithDebInfo\"" -Xcompiler "/EHsc /W1 /nologo /O2 /FdE:\Zhansheng\software\installed\tiny-cuda-nn\build\src\RelWithDebInfo\tiny-cuda-nn.pdb /FS /Zi  /MD /GR" -o tiny-cuda-nn.dir\RelWithDebInfo\common_device.obj "E:\Zhansheng\software\installed\tiny-cuda-nn\src\common_device.cu" 
  
  E:\Zhansheng\software\installed\tiny-cuda-nn\build\src>"E:\Zhansheng\software\installed\NVDIA-GPU-computing-toolkit\CUDA\v11.3\bin\nvcc.exe" -gencode=arch=compute_86,code=\"compute_86,compute_86\" -gencode=arch=compute_86,code=\"sm_86,compute_86\" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64" -x cu   -I"E:\Zhansheng\software\installed\tiny-cuda-nn\include" -I"E:\Zhansheng\software\installed\tiny-cuda-nn\dependencies" -I"E:\Zhansheng\software\installed\tiny-cuda-nn\dependencies\cutlass\include" -I"E:\Zhansheng\software\installed\tiny-cuda-nn\dependencies\cutlass\tools\util\include" -I"E:\Zhansheng\software\installed\NVDIA-GPU-computing-toolkit\CUDA\v11.3\include"     --keep-dir x64\RelWithDebInfo  -maxrregcount=0  --machine 64 --compile -cudart static --extended-lambda --expt-relaxed-constexpr -std=c++14 -Xcompiler="/EHsc -Zi -Ob1"   -D_WINDOWS -DNDEBUG -DTCNN_MIN_GPU_ARCH=86 -DTCNN_SHAMPOO -D"CMAKE_INTDIR=\"RelWithDebInfo\"" -D_MBCS -D"CMAKE_INTDIR=\"RelWithDebInfo\"" -Xcompiler "/EHsc /W1 /nologo /O2 /FdE:\Zhansheng\software\installed\tiny-cuda-nn\build\src\RelWithDebInfo\tiny-cuda-nn.pdb /FS /Zi  /MD /GR" -o tiny-cuda-nn.dir\RelWithDebInfo\cpp_api.obj "E:\Zhansheng\software\installed\tiny-cuda-nn\src\cpp_api.cu" 
  Compiling CUDA source file ..\..\src\fully_fused_mlp.cu...
  
  E:\Zhansheng\software\installed\tiny-cuda-nn\build\src>"E:\Zhansheng\software\installed\NVDIA-GPU-computing-toolkit\CUDA\v11.3\bin\nvcc.exe" -gencode=arch=compute_86,code=\"compute_86,compute_86\" -gencode=arch=compute_86,code=\"sm_86,compute_86\" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64" -x cu   -I"E:\Zhansheng\software\installed\tiny-cuda-nn\include" -I"E:\Zhansheng\software\installed\tiny-cuda-nn\dependencies" -I"E:\Zhansheng\software\installed\tiny-cuda-nn\dependencies\cutlass\include" -I"E:\Zhansheng\software\installed\tiny-cuda-nn\dependencies\cutlass\tools\util\include" -I"E:\Zhansheng\software\installed\NVDIA-GPU-computing-toolkit\CUDA\v11.3\include"     --keep-dir x64\RelWithDebInfo  -maxrregcount=0  --machine 64 --compile -cudart static --extended-lambda --expt-relaxed-constexpr -std=c++14 -Xcompiler="/EHsc -Zi -Ob1"   -D_WINDOWS -DNDEBUG -DTCNN_MIN_GPU_ARCH=86 -DTCNN_SHAMPOO -D"CMAKE_INTDIR=\"RelWithDebInfo\"" -D_MBCS -D"CMAKE_INTDIR=\"RelWithDebInfo\"" -Xcompiler "/EHsc /W1 /nologo /O2 /FdE:\Zhansheng\software\installed\tiny-cuda-nn\build\src\RelWithDebInfo\tiny-cuda-nn.pdb /FS /Zi  /MD /GR" -o tiny-cuda-nn.dir\RelWithDebInfo\encoding.obj "E:\Zhansheng\software\installed\tiny-cuda-nn\src\encoding.cu" 
  
  E:\Zhansheng\software\installed\tiny-cuda-nn\build\src>"E:\Zhansheng\software\installed\NVDIA-GPU-computing-toolkit\CUDA\v11.3\bin\nvcc.exe" -gencode=arch=compute_86,code=\"compute_86,compute_86\" -gencode=arch=compute_86,code=\"sm_86,compute_86\" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64" -x cu   -I"E:\Zhansheng\software\installed\tiny-cuda-nn\include" -I"E:\Zhansheng\software\installed\tiny-cuda-nn\dependencies" -I"E:\Zhansheng\software\installed\tiny-cuda-nn\dependencies\cutlass\include" -I"E:\Zhansheng\software\installed\tiny-cuda-nn\dependencies\cutlass\tools\util\include" -I"E:\Zhansheng\software\installed\NVDIA-GPU-computing-toolkit\CUDA\v11.3\include"     --keep-dir x64\RelWithDebInfo  -maxrregcount=0  --machine 64 --compile -cudart static --extended-lambda --expt-relaxed-constexpr -std=c++14 -Xcompiler="/EHsc -Zi -Ob1"   -D_WINDOWS -DNDEBUG -DTCNN_MIN_GPU_ARCH=86 -DTCNN_SHAMPOO -D"CMAKE_INTDIR=\"RelWithDebInfo\"" -D_MBCS -D"CMAKE_INTDIR=\"RelWithDebInfo\"" -Xcompiler "/EHsc /W1 /nologo /O2 /FdE:\Zhansheng\software\installed\tiny-cuda-nn\build\src\RelWithDebInfo\tiny-cuda-nn.pdb /FS /Zi  /MD /GR" -o tiny-cuda-nn.dir\RelWithDebInfo\network.obj "E:\Zhansheng\software\installed\tiny-cuda-nn\src\network.cu" 
  
  E:\Zhansheng\software\installed\tiny-cuda-nn\build\src>"E:\Zhansheng\software\installed\NVDIA-GPU-computing-toolkit\CUDA\v11.3\bin\nvcc.exe" -gencode=arch=compute_86,code=\"compute_86,compute_86\" -gencode=arch=compute_86,code=\"sm_86,compute_86\" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64" -x cu   -I"E:\Zhansheng\software\installed\tiny-cuda-nn\include" -I"E:\Zhansheng\software\installed\tiny-cuda-nn\dependencies" -I"E:\Zhansheng\software\installed\tiny-cuda-nn\dependencies\cutlass\include" -I"E:\Zhansheng\software\installed\tiny-cuda-nn\dependencies\cutlass\tools\util\include" -I"E:\Zhansheng\software\installed\NVDIA-GPU-computing-toolkit\CUDA\v11.3\include"     --keep-dir x64\RelWithDebInfo  -maxrregcount=0  --machine 64 --compile -cudart static --extended-lambda --expt-relaxed-constexpr -std=c++14 -Xcompiler="/EHsc -Zi -Ob1"   -D_WINDOWS -DNDEBUG -DTCNN_MIN_GPU_ARCH=86 -DTCNN_SHAMPOO -D"CMAKE_INTDIR=\"RelWithDebInfo\"" -D_MBCS -D"CMAKE_INTDIR=\"RelWithDebInfo\"" -Xcompiler "/EHsc /W1 /nologo /O2 /FdE:\Zhansheng\software\installed\tiny-cuda-nn\build\src\RelWithDebInfo\tiny-cuda-nn.pdb /FS /Zi  /MD /GR" -o tiny-cuda-nn.dir\RelWithDebInfo\cutlass_mlp.obj "E:\Zhansheng\software\installed\tiny-cuda-nn\src\cutlass_mlp.cu" 
  
  E:\Zhansheng\software\installed\tiny-cuda-nn\build\src>"E:\Zhansheng\software\installed\NVDIA-GPU-computing-toolkit\CUDA\v11.3\bin\nvcc.exe" -gencode=arch=compute_86,code=\"compute_86,compute_86\" -gencode=arch=compute_86,code=\"sm_86,compute_86\" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64" -x cu   -I"E:\Zhansheng\software\installed\tiny-cuda-nn\include" -I"E:\Zhansheng\software\installed\tiny-cuda-nn\dependencies" -I"E:\Zhansheng\software\installed\tiny-cuda-nn\dependencies\cutlass\include" -I"E:\Zhansheng\software\installed\tiny-cuda-nn\dependencies\cutlass\tools\util\include" -I"E:\Zhansheng\software\installed\NVDIA-GPU-computing-toolkit\CUDA\v11.3\include"     --keep-dir x64\RelWithDebInfo  -maxrregcount=0  --machine 64 --compile -cudart static --extended-lambda --expt-relaxed-constexpr -std=c++14 -Xcompiler="/EHsc -Zi -Ob1"   -D_WINDOWS -DNDEBUG -DTCNN_MIN_GPU_ARCH=86 -DTCNN_SHAMPOO -D"CMAKE_INTDIR=\"RelWithDebInfo\"" -D_MBCS -D"CMAKE_INTDIR=\"RelWithDebInfo\"" -Xcompiler "/EHsc /W1 /nologo /O2 /FdE:\Zhansheng\software\installed\tiny-cuda-nn\build\src\RelWithDebInfo\tiny-cuda-nn.pdb /FS /Zi  /MD /GR" -o tiny-cuda-nn.dir\RelWithDebInfo\object.obj "E:\Zhansheng\software\installed\tiny-cuda-nn\src\object.cu" 
  
  E:\Zhansheng\software\installed\tiny-cuda-nn\build\src>"E:\Zhansheng\software\installed\NVDIA-GPU-computing-toolkit\CUDA\v11.3\bin\nvcc.exe" -gencode=arch=compute_86,code=\"compute_86,compute_86\" -gencode=arch=compute_86,code=\"sm_86,compute_86\" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64" -x cu   -I"E:\Zhansheng\software\installed\tiny-cuda-nn\include" -I"E:\Zhansheng\software\installed\tiny-cuda-nn\dependencies" -I"E:\Zhansheng\software\installed\tiny-cuda-nn\dependencies\cutlass\include" -I"E:\Zhansheng\software\installed\tiny-cuda-nn\dependencies\cutlass\tools\util\include" -I"E:\Zhansheng\software\installed\NVDIA-GPU-computing-toolkit\CUDA\v11.3\include"     --keep-dir x64\RelWithDebInfo  -maxrregcount=0  --machine 64 --compile -cudart static --extended-lambda --expt-relaxed-constexpr -std=c++14 -Xcompiler="/EHsc -Zi -Ob1"   -D_WINDOWS -DNDEBUG -DTCNN_MIN_GPU_ARCH=86 -DTCNN_SHAMPOO -D"CMAKE_INTDIR=\"RelWithDebInfo\"" -D_MBCS -D"CMAKE_INTDIR=\"RelWithDebInfo\"" -Xcompiler "/EHsc /W1 /nologo /O2 /FdE:\Zhansheng\software\installed\tiny-cuda-nn\build\src\RelWithDebInfo\tiny-cuda-nn.pdb /FS /Zi  /MD /GR" -o tiny-cuda-nn.dir\RelWithDebInfo\loss.obj "E:\Zhansheng\software\installed\tiny-cuda-nn\src\loss.cu" 
  
  E:\Zhansheng\software\installed\tiny-cuda-nn\build\src>"E:\Zhansheng\software\installed\NVDIA-GPU-computing-toolkit\CUDA\v11.3\bin\nvcc.exe" -gencode=arch=compute_86,code=\"compute_86,compute_86\" -gencode=arch=compute_86,code=\"sm_86,compute_86\" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64" -x cu   -I"E:\Zhansheng\software\installed\tiny-cuda-nn\include" -I"E:\Zhansheng\software\installed\tiny-cuda-nn\dependencies" -I"E:\Zhansheng\software\installed\tiny-cuda-nn\dependencies\cutlass\include" -I"E:\Zhansheng\software\installed\tiny-cuda-nn\dependencies\cutlass\tools\util\include" -I"E:\Zhansheng\software\installed\NVDIA-GPU-computing-toolkit\CUDA\v11.3\include"     --keep-dir x64\RelWithDebInfo  -maxrregcount=0  --machine 64 --compile -cudart static --extended-lambda --expt-relaxed-constexpr -std=c++14 -Xcompiler="/EHsc -Zi -Ob1"   -D_WINDOWS -DNDEBUG -DTCNN_MIN_GPU_ARCH=86 -DTCNN_SHAMPOO -D"CMAKE_INTDIR=\"RelWithDebInfo\"" -D_MBCS -D"CMAKE_INTDIR=\"RelWithDebInfo\"" -Xcompiler "/EHsc /W1 /nologo /O2 /FdE:\Zhansheng\software\installed\tiny-cuda-nn\build\src\RelWithDebInfo\tiny-cuda-nn.pdb /FS /Zi  /MD /GR" -o tiny-cuda-nn.dir\RelWithDebInfo\optimizer.obj "E:\Zhansheng\software\installed\tiny-cuda-nn\src\optimizer.cu" 
  
  E:\Zhansheng\software\installed\tiny-cuda-nn\build\src>"E:\Zhansheng\software\installed\NVDIA-GPU-computing-toolkit\CUDA\v11.3\bin\nvcc.exe" -gencode=arch=compute_86,code=\"compute_86,compute_86\" -gencode=arch=compute_86,code=\"sm_86,compute_86\" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64" -x cu   -I"E:\Zhansheng\software\installed\tiny-cuda-nn\include" -I"E:\Zhansheng\software\installed\tiny-cuda-nn\dependencies" -I"E:\Zhansheng\software\installed\tiny-cuda-nn\dependencies\cutlass\include" -I"E:\Zhansheng\software\installed\tiny-cuda-nn\dependencies\cutlass\tools\util\include" -I"E:\Zhansheng\software\installed\NVDIA-GPU-computing-toolkit\CUDA\v11.3\include"     --keep-dir x64\RelWithDebInfo  -maxrregcount=0  --machine 64 --compile -cudart static --extended-lambda --expt-relaxed-constexpr -std=c++14 -Xcompiler="/EHsc -Zi -Ob1"   -D_WINDOWS -DNDEBUG -DTCNN_MIN_GPU_ARCH=86 -DTCNN_SHAMPOO -D"CMAKE_INTDIR=\"RelWithDebInfo\"" -D_MBCS -D"CMAKE_INTDIR=\"RelWithDebInfo\"" -Xcompiler "/EHsc /W1 /nologo /O2 /FdE:\Zhansheng\software\installed\tiny-cuda-nn\build\src\RelWithDebInfo\tiny-cuda-nn.pdb /FS /Zi  /MD /GR" -o tiny-cuda-nn.dir\RelWithDebInfo\reduce_sum.obj "E:\Zhansheng\software\installed\tiny-cuda-nn\src\reduce_sum.cu" 
  
  E:\Zhansheng\software\installed\tiny-cuda-nn\build\src>"E:\Zhansheng\software\installed\NVDIA-GPU-computing-toolkit\CUDA\v11.3\bin\nvcc.exe" -gencode=arch=compute_86,code=\"compute_86,compute_86\" -gencode=arch=compute_86,code=\"sm_86,compute_86\" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64" -x cu   -I"E:\Zhansheng\software\installed\tiny-cuda-nn\include" -I"E:\Zhansheng\software\installed\tiny-cuda-nn\dependencies" -I"E:\Zhansheng\software\installed\tiny-cuda-nn\dependencies\cutlass\include" -I"E:\Zhansheng\software\installed\tiny-cuda-nn\dependencies\cutlass\tools\util\include" -I"E:\Zhansheng\software\installed\NVDIA-GPU-computing-toolkit\CUDA\v11.3\include"     --keep-dir x64\RelWithDebInfo  -maxrregcount=0  --machine 64 --compile -cudart static --extended-lambda --expt-relaxed-constexpr -std=c++14 -Xcompiler="/EHsc -Zi -Ob1"   -D_WINDOWS -DNDEBUG -DTCNN_MIN_GPU_ARCH=86 -DTCNN_SHAMPOO -D"CMAKE_INTDIR=\"RelWithDebInfo\"" -D_MBCS -D"CMAKE_INTDIR=\"RelWithDebInfo\"" -Xcompiler "/EHsc /W1 /nologo /O2 /FdE:\Zhansheng\software\installed\tiny-cuda-nn\build\src\RelWithDebInfo\tiny-cuda-nn.pdb /FS /Zi  /MD /GR" -o tiny-cuda-nn.dir\RelWithDebInfo\fully_fused_mlp.obj "E:\Zhansheng\software\installed\tiny-cuda-nn\src\fully_fused_mlp.cu" 
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\xutility(1309): **error :** expected a "(" [E:\Zhansheng\software\installed\tiny-cuda-nn\build\src\tiny-cuda-nn.vcxproj]
            detected during instantiation of "void std::_Adl_verify_range(const _Iter &, const _Sentinel &) [with _Iter=const char *, _Sentinel=const char *]" 
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\xlocale(1990): here
  
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\xutility(1310): **error :** identifier "_Verify_range" is undefined [E:\Zhansheng\software\installed\tiny-cuda-nn\build\src\tiny-cuda-nn.vcxproj]
            detected during instantiation of "void std::_Adl_verify_range(const _Iter &, const _Sentinel &) [with _Iter=const char *, _Sentinel=const char *]" 
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\xlocale(1990): here
  
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\xutility(1309): **error :** expected a "(" [E:\Zhansheng\software\installed\tiny-cuda-nn\build\src\tiny-cuda-nn.vcxproj]
            detected during instantiation of "void std::_Adl_verify_range(const _Iter &, const _Sentinel &) [with _Iter=__wchar_t *, _Sentinel=__wchar_t *]" 
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\xlocale(1991): here
  ...

Error log file: 
[build.log](https://github.com/NVlabs/tiny-cuda-nn/files/8427198/build.log)

Thanks for your contribution!

Regars

**Comment by vermouth599** [comment]
Have you solved this issue? I confronted with this problem ,too.

**Comment by hzhshok** [comment]
@vermouth599 Hello, 
I dont' rembered the detailed  at that time it is the code bug or not, if yes, so please update to other version,  if not, so i just give some hints to confirm if it comes code bug or used build environment.

a. **CMake** i used 3.22.x, using 3.23.x maybe it can't pass build at a specific duration.
   I don't remembered it is nvdiffrec or instant-ngp for this limit or not, but cmake 3.22 is the best for me at the beginning of the 
   year.
   You can check the happened issueses to confirm if it had this issue or not.
b. Please confirm if you used the suitable **VS environment**, which seems like it is from native SDK.
    Please use VS console(with VS environment) starting up by menu or set up the environment  for console terminal using the 
    .bat inside VS installation.
c.  Confirm **cuda version**, i used cuda 11.3 to match the latest **stable** pytorch(at that time maybe 1.11, now pytorch 1.12 should be stable for cuda 11.6, but i did not try that).
     Once I used cuda 11.6 to match 1.11 under windows and ubuntu,  but failed, and switch to 11.3 it passed, so i keeped on 
     cuda 11.3.

Wish to give a hint.

Regards

**Comment by hzhshok** [comment]
Just closed since i solved it by myself-environment.

Regards

**Comment by vermouth599** [comment]
Thank you! The problem solved when I update the codes ! And it does work!
