### ISSUE TITLE
`linear_kernel` truncates `n_elements` to `uint32_t`

### ISSUE THREAD

**Issue by igozali** [NVlabs/tiny-cuda-nn#79]
Hi folks, the `linear_kernel` call downcasts (or upcasts it too I suppose) `n_elements` to `uint32_t` in here:

https://github.com/NVlabs/tiny-cuda-nn/blob/master/include/tiny-cuda-nn/common.h#L288

So if I call this with something that has more than the max allowed value of `uint32_t`, it overflows. 

Could we not just keep the type of `n_elements` the same, e.g. like this:
```diff
--- a/include/tiny-cuda-nn/common.h
+++ b/include/tiny-cuda-nn/common.h
@@ -285,7 +285,7 @@ inline void linear_kernel(K kernel, uint32_t shmem_size, cudaStream_t stream, T
        if (n_elements <= 0) {
                return;
        }
-       kernel<<<n_blocks_linear(n_elements), n_threads_linear, shmem_size, stream>>>((uint32_t)n_elements, args...);
+       kernel<<<n_blocks_linear(n_elements), n_threads_linear, shmem_size, stream>>>(n_elements, args...);
 }
```

**Comment by Tom94** [comment]
Thanks for catching this! To be honest, I'm scratching my head about why this didn't break a bunch of things we are doing with >4b elements, but it's fixed with https://github.com/NVlabs/tiny-cuda-nn/commit/8e428f87d45ba34e65354d9881b46e9b3c286f31 in any case.
