### ISSUE TITLE
namespace "std" has no member "lcm"	tiny-cuda-nn	 

### ISSUE THREAD

**Issue by dumpinfo** [NVlabs/tiny-cuda-nn#8]
void set_alignment(uint32_t alignment) override {
		alignment = std::lcm(alignment, min_alignment());
		m_n_padded_output_dims = next_multiple(m_n_output_dims, alignment);
		m_n_to_pad = m_n_padded_output_dims - m_n_output_dims;
	}

the command line is:
"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.5\bin\nvcc.exe" -gencode=arch=compute_86,code=\"compute_86,compute_86\" -gencode=arch=compute_86,code=\"sm_86,compute_86\" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64" -x cu   -I"N:\Test\tiny-cuda-nn\include" -I"N:\Test\tiny-cuda-nn\dependencies" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.5\include"     --keep-dir x64\Debug  -maxrregcount=0  --machine 64 --compile -cudart static --extended-lambda --expt-relaxed-constexpr -Xcompiler="/EHsc -Zi -Ob0" -g  -D_WINDOWS -D"CMAKE_INTDIR=\"Debug\"" -D"CMAKE_INTDIR=\"Debug\"" -D_MBCS -Xcompiler "/EHsc /W1 /nologo /Od /FdN:\Test\tiny-cuda-nn\build\src\Debug\tiny-cuda-nn.pdb /FS /Zi /RTC1 /MDd /GR" -o tiny-cuda-nn.dir\Debug\encoding.obj "N:\Test\tiny-cuda-nn\src\encoding.cu"”  1。	tiny-cuda-nn	C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\BuildCustomizations\CUDA 11.5.targets	785	

enviroment:
visual c++ 2019, cmake 3.18 
windows 10

**Comment by Tom94** [comment]
`std::lcm` is a C++17 feature -- I suspect C++17 is not correctly enabled in your setup. This looks like the same problem as in your other issue #9 , where the lack of `std::filesystem` is another indicator of a missing C++17 compiler flag. (or a too old compiler)

**Comment by dumpinfo** [comment]
> 

would you pls list your compile enviroment ? 
egs: which visual c++ version, which cmake & windows &cuda version, and what compiler option should be setted in vs studio?

**Comment by Tom94** [comment]
You can see a minimal compiling example (for both Windows and Linux) [here](https://github.com/NVlabs/tiny-cuda-nn/blob/master/.github/workflows/main.yml).

Here are the corresponding compiler logs from `master`: https://github.com/NVlabs/tiny-cuda-nn/actions/runs/1618735536

**Comment by Tom94** [comment]
Closing, since __tiny-cuda-nn__ no longer requires c++17
