### ISSUE TITLE
Uncaught exception - Memory Allocation

### ISSUE THREAD

**Issue by nopor** [NVlabs/tiny-cuda-nn#82]
Error:
`ERROR    Uncaught exception: Could not allocate memory: ~/instant-ngp/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:112 cudaMalloc(&rawptr, n_bytes+DEBUG_GUARD_SIZE*2) failed with error out of memory`

Description/how to reproduce:
When adjusting the marching cubes mesh output (in https://github.com/NVlabs/instant-ngp), all resolutions roughly above 768^3 fail with the exception stated above.
This happens regardless of the scene/used data.

(Additional info: tried it on a 3090)
(Hope this is the correct repo to report this)

**Comment by Tom94** [comment]
As the error says: you're running out of memory. In order to export larger resolutions, you need to either free up GPU RAM elsewhere or obtain a GPU with more RAM (short of optimizing the algorithm). Cheers!

**Comment by nopor** [comment]
Can monitor the RAM and GPU memory usage when trying this, but I really doubt that it's the case.
As I've mentioned, it's running on a 3090. Alongside with it are 64GB RAM.

**Comment by Tom94** [comment]
Yes, the 24 GB of GPU RAM on your 3090 can easily be exhausted by cranking the marching cubes resolution too high. The 64 GB CPU-side RAM are irrelevant in this context.

**Comment by nopor** [comment]
Yes, true - re-read the memory part afterwards.
Nevertheless will be able to check the memory consumption later on and will see what can be done. Though idealy the application shouldn't crash and scale dynamically. Wdyt?

**Comment by nopor** [comment]
Forgot to thank you for your quick replies, @Tom94 .
Retried it with the synthetic data sets (the lego one for example) and it can mesh it up to 1104^3 using ~23.7GB/24GB of the dedicated gpu memory and ~0.7GB/32GB of the shared gpu memory during the meshing process.
Everything above that unfortunately doesn't work.
So, thanks for clarifying it.

**Comment by gvbgeomatics** [comment]
We tested with 49CPUs, 192GB RAM and 4GPUs (16GiB) each but encountered the same error. It's a bug which needs to be fixed.

**Comment by Tom94** [comment]
It's not a bug. 16 GiB of GPU RAM can easily be exhausted by using a high marching cubes resolution.

**Comment by gvbgeomatics** [comment]
We will test with a higher configuration and let you know. Thanks
