### ISSUE TITLE
dependencies/cutlass not included in v1.5 release tarball (&zip)

### ISSUE THREAD

**Issue by libreliu** [NVlabs/tiny-cuda-nn#87]
Hi,
Thanks for this awesome library!
It seems that dependencies/cutlass was not included in the release tarball (an empty folder for all we can get). I'm wondering if you've forget to put it in since it's git-submoduled.

**Comment by libreliu** [comment]
Thanks! I've cloned and checkout to the tag exactly as you've described.

Also, it could possibly be of some help if this repository could setup a GitHub workflow (or manually done by humans after each release) to archive the source code upload the tarball as binary asset, as a similar (but not exactly the same) scenario [here](https://github.com/SHTOOLS/SHTOOLS/issues/262) pointed out.

**Comment by Tom94** [comment]
I feel like the automatically-generated release-associated source code tarballs are used rarely enough that it's not worth the effort to work around them not including submodules -- gonna close this one for now.
