### ISSUE TITLE
RuntimError: DifferentiableObject::backward_backward_input_impl: not implemented error

### ISSUE THREAD

**Issue by jseobyun** [NVlabs/tiny-cuda-nn#89]
Hi, thank you for sharing the awesome work.

I'm trying to re-implement Neus : Learning Neural Implicit Surfaces by Volume Rendering for Multi-view Reconstruction base on your tiny-cuda-nn.

At the last debug stage, I met the error as follows:

```
Traceback (most recent call last):
  File "run.py", line 338, in <module>
    runner.train()
  File "run.py", line 122, in train
    loss.backward()
  File "/opt/conda/lib/python3.8/site-packages/torch/_tensor.py", line 352, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/function.py", line 199, in apply
    return user_fn(self, *args)
  File "/opt/conda/lib/python3.8/site-packages/tinycudann-1.6-py3.8-linux-x86_64.egg/tinycudann/modules.py", line 78, in backward
    doutput_grad, weight_grad, input_grad = ctx.ctx_fwd.native_tcnn_module.bwd_bwd_input(
RuntimeError: DifferentiableObject::backward_backward_input_impl: not implemented error
```
And I don't have any idea to solve this issue. 

My guesses are,

1. Among 3 networks that I implemented, 1 network has concatenation between torch tensor and output of tcnn.Network.  like this,
```
    def forward(self, points, normals, view_dirs, feature_vector):        
        # self.encoder and self.backbone are tcnn.Encoding and tcnn.Network
        view_dirs = self.encoder(view_dirs) 
        x = torch.cat([points, view_dirs, normals, feature_vector], dim=-1)        
        x = self.backbone(x) 
        return x
```
Does the concatenation between torch tensor and output of tcnn.Network causes the error??

2.  The output of tcnn.Network is feeding to torch network vice versa.
Does the operation (e.g. + - % x) between torch tensor and output of tcnn.Network causes the error?

Could you help me to understand the cause of this error? I want to implement the code avoiding this.

Thanks in advance,

**Comment by Tom94** [comment]
Hi there, __tiny-cuda-nn__ networks don't support double-backward. The only component that does is the hash encoding. Cheers!

**Comment by jseobyun** [comment]
> Hi there, **tiny-cuda-nn** networks don't support double-backward. The only component that does is the hash encoding. Cheers!

Thank you for quick reply ! But, I'm still confused... 

Could you give me more hints? 

For example, when double-backward occurs using tiny-cuda-nn....

Sorry for bothering you.

**Comment by jseobyun** [comment]
Thank you! I solved it~!

**Comment by coder4869** [comment]
> Thank you! I solved it~!

Hello, I met the same error, how did you fixed it ?

**Comment by lt-xiang** [comment]
> Thank you! I solved it~!

hello, I have the same problem, could you share your solution ?thanks
