### ISSUE TITLE
fatal error: filesystem: No such file or directory

### ISSUE THREAD

**Issue by dumpinfo** [NVlabs/tiny-cuda-nn#9]
json.hpp:3954:14: fatal error: filesystem: No such file or directory
     #include <filesystem>
              ^~~~~~~~~~~~
compilation terminated.
src/CMakeFiles/tiny-cuda-nn.dir/build.make:103: recipe for target 'src/CMakeFiles/tiny-cuda-nn.dir/cutlass_mlp.cu.o' failed
make[2]: *** [src/CMakeFiles/tiny-cuda-nn.dir/cutlass_mlp.cu.o] Error 1
CMakeFiles/Makefile2:133: recipe for target 'src/CMakeFiles/tiny-cuda-nn.dir/all' failed
make[1]: *** [src/CMakeFiles/tiny-cuda-nn.dir/all] Error 2

enviroment:
ubuntu 18.04 
cuda-11.0
gtx 1080

**Comment by dumpinfo** [comment]
when i add "experimental" before  filesystem 
#include <experimental/filesystem>
the errors seems be skipped.
but other more errors show as bellow : 
[  5%] Building CUDA object src/CMakeFiles/tiny-cuda-nn.dir/cutlass_mlp.cu.o
/disk3/test/tiny-cuda-nn/dependencies/json/json.hpp(4384): error: name followed by "::" must be a class or namespace name

/disk3/test/tiny-cuda-nn/dependencies/json/json.hpp(5007): error: name followed by "::" must be a class or namespace name

^C
2 errors detected in the compilation of "/disk3/test/tiny-cuda-nn/src/cutlass_mlp.cu".
Compilation terminated.
src/CMakeFiles/tiny-cuda-nn.dir/build.make:103: recipe for target 'src/CMakeFiles/tiny-cuda-nn.dir/cutlass_mlp.cu.o' failed

**Comment by Tom94** [comment]
See my response to the above issue. `std::filesystem` is a C++17 feature. The lack of support from your compiler suggests a missing flag and/or a too old compiler version.

**Comment by dumpinfo** [comment]
> See my response to the above issue. `std::filesystem` is a C++17 feature. The lack of support from your compiler suggests a missing flag and/or a too old compiler version.

the problem is solved by upgrade cmake to 3.22 on win10 with vs2019

**Comment by Tom94** [comment]
That's great to know, thank you for diagnosing this! I'll have a closer look at which specific cmake version fixes the problem and will update the README accordingly.
