### ISSUE TITLE
Trainer::forward number of parameters

### ISSUE THREAD

**Issue by ookey** [NVlabs/tiny-cuda-nn#92]
hello,
thanks for the outstanding work!

I was wondering if the call to `Trainer::forward` did not contain a bug related to the number of parameters it is given.
line 158 of `trainer.h`:
```
	void forward(const float loss_scale, const GPUMatrixDynamic<T>& input, const GPUMatrix<float>& target, const GPUMatrix<float>* data_pdf = nullptr, float* loss_value = nullptr) {
		forward(nullptr, loss_scale, input, target, data_pdf, loss_value);
	}
```
the call to `forward` contains 6 parameters including `loss_value` whereas this parameter has disappeared from the signature since 6ea87fc701cac7d2c4dc9695a97bbcb959c388b0 if I understood well.

If I'm right, I can't understand it compiles at all (if any expert has an explanation of this latter point, I'd be interested).

Best regards,
Matthieu.

**Comment by Tom94** [comment]
Good catch! It compiled as long as the faulty overload of `forward` is never called, because `Trainer<T>` is a template and its methods are this only lazily instantiated by the compiler. Will make a pass fixing those.
