### ISSUE TITLE
nvcc fatal   : Unknown option '-extended-lambda' on cuda10.0

### ISSUE THREAD

**Issue by soolone** [NVlabs/tiny-cuda-nn#94]
Ubuntu 18.04
GPU: RTX2080Ti
cuda_version: 10.0
python: 3.6.9
torch_version: 1.7.1

Hello, thank you for your great works!
When I tried to build a Pytorch Extention by:

"pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch"

but got an error:

/data/cuda/cuda-10.0/cuda/bin/nvcc -I/data/nvdiffrec/tiny-cuda-nn/include -I/data/nvdiffrec/tiny-cuda-nn/dependencies -I/data/nvdiffrec/tiny-cuda-nn/dependencies/cutlass/include -I/data/nvdiffrec/tiny-cuda-nn/dependencies/cutlass/tools/util/include -I/home/shuaijuncheng/.local/lib/python3.6/site-packages/torch/include -I/home/shuaijuncheng/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/shuaijuncheng/.local/lib/python3.6/site-packages/torch/include/TH -I/home/shuaijuncheng/.local/lib/python3.6/site-packages/torch/include/THC -I/data/cuda/cuda-10.0/cuda/include -I/usr/include/python3.6m -c ../../src/cpp_api.cu -o build/temp.linux-x86_64-3.6/../../src/cpp_api.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -std=c++14 --extended-lambda --expt-relaxed-constexpr -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 -Xcompiler=-mf16c -Xcompiler=-Wno-float-conversion -Xcompiler=-fno-strict-aliasing -DTCNN_MIN_GPU_ARCH=75 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0
nvcc fatal   : Unknown option '-extended-lambda' 
error: command '/data/cuda/cuda-10.0/cuda/bin/nvcc' failed with exit status 1

Are there any requirements for the CUDA version?
If yes, check whether a version of cuda10.0 is available?

**Comment by Tom94** [comment]
__tiny-cuda-nn__ requires at least CUDA 10.2 -- please feel free to re-open the issue if the issue persists after upgrading. Cheers!
